class LocatorsFleetTelematicsCenterPage:
    iframe_class = 'telematicsFrame'
    more_charts_button = 'dashboard_MoreCharts'

    # Dashboard page
    show_hidden_reports_id = 'dashboard_AddReport'
    eld_unverified_logs_xpath = '//*[@title="ELD Unverified Logs"]'
    hos_violation_breakdown_xpath = '//*[@title="HOS Violation Breakdown"]'
    safety_xpath = '//*[text()="Safety"]'


    # Map page
    search_asset_id = 'checkmateMapSearch'
    nearest_xpath = '//*[text()="Nearest"]'
    status_dropdown_id = 'liveMap_viewAssetStatus'
    saved_views_id = 'liveMap_viewMapViews'
    find_asset_xpath = '//*[@placeholder="Find asset"]'
    status_change_sort_direction_xpath = '//*[@title="Change sort direction"]'
    sort_by_dropdown_icon_xpath = '//*[@title="Sort by"]'
    distance_option_text_xpath = '//button[text()="Distance"]'
    exceptions_option_text_xpath = '//button[text()="Exceptions"]'
    update_list_with_map_checkbox_xpath = '(//*[text()="Update list with map"])[1]'
    map_option_setting_xpath = '//*[text()="Map options"]'
    add_zone_xpath = '//*[text()="Add zone"]'
    mc_refresh_icon_id = 'liveVehiclesLayer_updateButton'
    mc_zoom_in_xpath = '//*[@title="Zoom in"]'
    mc_zoom_out_xpath = '//*[@title="Zoom out"]'

    # Productivity - Trip History page
    trip_history_header_id = 'tripsHistoryHeader'
    search_bar_id = 'tripsHistory_FilterBox'
    select_different_options_xpath = '//*[@title="Select different options"]'
    live_positions_id = 'tripsHistory_LiveButton_newUI'
    reports_id = 'tripsHistory_reports'
    show_all_trips_xpath = '//*[text()="Show all trips"]'
    date_xpath = '//*[@class="geo-trip-date-range__date-link"]'

    # Productivity - Routes >> Routes page
    routes_header_xpath = '//span[text()="Routes"]'
    routes_search_id = 'routes_SearchId'
    routes_addnewroute_id = 'routes_AddNewRouteId'
    routes_filter_xpath = '//*[@id="routes_OptionsButtonId"]'
    routes_columns_id = 'routeList_editColumns'
    routes_reset_to_default_xpath = '//*[@title="Reset to default"]'
    routes_name_xpath = '//*[text()="Name"]'
    routes_assigned_asset_xpath = '//*[text()="Assigned Asset"]'
    routes_scheduled_start_time_xpath = '//*[text()="Scheduled Start Time"]'
    routes_status_xpath = '//*[text()="Status"]'

    # Productivity - Routes >> Planned vs Actual page
    plannedvsactual_header_xpath = '//*[text()="Planned vs. actual route report"]'
    pa_search_assets_xpath = '//*[@placeholder="Search"]'
    pa_options_dropdown_id = 'routePlanActual_OptionButton'
    pa_report_dropdown_id = 'routePlan_reports'

    # Productivity - Routes >> Route Summary page
    route_summary_report_header_xpath = '//*[@class="geo-page-header"]//*[text()="Route Summary Report"]'
    rs_options_id = 'routeSummaryReport_OptionsButtonId'
    rs_stop_processing_id = 'routeSummaryReport_StopProcessing'
    rs_reports_id = 'routeSummary_reports'
    rs_display_table_xpath = '(//*[text()="Display Options"])[2]'
    rs_asset_xpath = '//*[text()="Assets"]'

    # Productivity - Routes >> Unmatched Route page
    unmatched_route_header_xpath = '//*[@class="geo-page-header"]//*[text()="Unmatched Route"]'
    ur_options_id = 'unmatchedRoute_OptionsButtonId'
    ur_reports_id = 'unmatchedRoute_reports'

    # Productivity - Routes >> Import Routes page
    import_routes_header_xpath = '//*[@class="geo-page-header"]//*[text()="Import Routes"]'
    drop_file_id = 'dropArea'
    import_file_table_xpath = '//*[@class="import-example__table"]'

    # Productivity - Public Works >> Route Completion page
    route_completion_header_xpath = '//*[@id= "pageNameId"]'
    rc_options_dropdown_xpath = '//*[text()= "Options"]'
    rc_report_dropdown_xpath = '//*[text()= "Report"]'
    reports_button_xpath = '//button//*[contains(text(), "Report")]'
    rc_settings_id = 'routeCompletionSettingsButton'
    rc_zoom_in_xpath = '//*[@title="Zoom in"]'
    rc_zoom_out_xpath = '//*[@title="Zoom out"]'

    # Productivity - Public Works >> Material Management page
    material_management_header_xpath = '//*[contains(text(), "Material Management")]//following::*[@class="geo-page-header__page-name"]'
    mm_options_dropdown_xpath = '//*[text()= "Options"]'
    mm_report_dropdown_xpath = '//*[text()= "Report"]'

    # Productivity - Zones >> Zones page
    zones_header_xpath = '//*[contains(text(), "Zones")]//following::*[@class="geo-page-header__page-name"]'
    zones_search_id = 'zones_SearchId'
    zones_filter_xpath = '//*[text()="Filter"]'
    filters_xpath = '//*[text()="Filters"]'
    zones_addnewzone_id = 'zones_AddNewZoneId'
    zones_types_id = 'zones_TypesButtonId'

    # Productivity - Zones >> Zone Visits page
    zonevisits_header_xpath = '//*[@class="geo-page-header"]//*[text()="Zone Visits"]'
    zv_search_assets_dropdown_id = 'zoneVisits_FilterBox'
    zv_sort_dropdown_id = 'zoneVisits_SortButtonSet'
    zv_summary_id = 'zoneVisits_switchReportTypeId'
    zv_options_dropdown_id = 'zoneVisits_OptionsButtonId'

    # Productivity - Zones >> Zone Types page
    zone_types_header_xpath = '(//*[text()="Zone Types"])[last()]'
    zt_add_zone_id = 'add-zone-type'
    zt_search_name_comment_xpath = '//*[@placeholder="Search"]'
    zone_types_customer_xpath = '//*[text()="Customer"]'
    zone_types_home_xpath = '//*[text()="Home"]'
    zone_types_inhouse_service_center_xpath = '//*[text()="In-house Service Center"]'
    zone_types_office_xpath = '//*[text()="Office"]'
    zone_types_vendor_service_center_xpath = '//*[text()="Vendor Service Center"]'

    # Productivity - Zones >> Import Zones page
    importzones_header_xpath = '//*[@class="geo-page-header"]//*[text()="Import Zones"]'
    importzones_options_id = 'importZones_AdditionalOptions'
    importzones_upload_id = 'importZones_UploaderId'
    importzones_table_xpath = '(//*[@class="importZones_exampleTable"])[1]'

    # Productivity - Driver Congregation page
    drivercongregation_header_xpath = '//*[@class="geo-header"]//*[text()="Driver Congregation"]'

    # Productivity - Asset Location Sharing page
    assetlocationsharing_header_xpath = '//*[@class="geo-page-header"]//*[text()="Asset Location Sharing"]'
    assetlocationsharing_sort_by_asset_id = 'assetLocationSharing_SortsId'

    # Productivity - Linked Assets page
    linkedassets_header_xpath = '//*[@class="zen-page-header__main-line"]//*[text()="Linked Assets"]'
    linkedassets_groups_xpath = '//*[@placeholder="Groups"]'
    linkedassets_primary_asset_xpath = '//*[text()="Primary asset"]'
    linkedassets_linked_asset_xpath = '//*[text()="Linked asset"]'

    # Productivity - Risk Management page
    riskmanagement_header_xpath = '//*[contains(@class, "geo-header")]//*[text()="Risk Management"]'
    options_xpath = '//*[text()="Options"]'

    # Compliance pages
    hoslogs_header_xpath = '//*[@class="geo-header"]//*[contains(text(), "HOS Logs")]'
    unidentifieddriving_header_xpath = '//*[@class="geo-header"]//*[text()="Unidentified Driving"]'
    hosviolations_header_xpath = '//*[@class="geo-header"]//*[text()="HOS Violations"]'
    hosavailability_header_xpath = '//*[@class="geo-header"]//*[text()="Driver Availability"]'
    timecardreport_header_xpath = '//*[@class="geo-header"]//*[text()="Time Card Report"]'
    iftareport_header_xpath = '//*[@class="geo-header"]//*[text()="IFTA Report"]'
    cleantruckcheckprogram_header_xpath = '//*[@class="geotab-page"]//*[text()="Clean Truck Check Program"]'
    enrollAssets_id = 'enrollAssets'

    # Maintenance pages
    assetinspection_header_xpath = '//*[@class="geo-header"]//*[text()="Asset Inspection"]'
    faults_header_xpath = '//*[@class="geo-page-header"]//*[text()="Faults"]'
    measurements_header_xpath = '//*[@class="geo-page-header"]//*[text()="Measurements"]'
    maintenanceschedules_header_xpath = '//*[@class="geotab-page maintenance-schedules-page"]//*[text()="Maintenance Schedules"]'
    work_order_management_page_title_xpath = '//h1[text()="Work Order Management" or class="zen-page-header__page-name"]'
    requests_tab_xpath = '//span[text()="Requests"]'
    orders_tab_xpath = '//span[text()="Orders"]'
    jobs_tab_xpath = '//span[text()="Jobs"]'
    schedules_button_xpath = '//div[@class="zen-main-header__adaptive-section"]//a[text()="Schedules"]'
    work_request_button_xpath = '(//*[contains(text(),"Work request")])[1]'
    group_filter_xpath = '//*[@placeholder="Groups"]'
    assets_filter_xpath = '//*[@placeholder="Assets"]'
    status_filter_xpath = '//*[@placeholder="Status"]'
    asset_column_title_xpath = '//*[text()="Asset"]'
    source_column_title_xpath = '//*[text()="Source"]'
    maintenance_type_column_title_xpath = '//*[text()="Maintenance type"]'
    categories_column_title_xpath = '//*[text()="Categories"]'
    severity_column_title_xpath = '//*[text()="Severity"]'
    triggered_column_title_xpath = '//*[text()="Triggered date"]'
    status_column_title_xpath = '//*[text()="Status"]'
    description_column_title_xpath = '//*[text()="Description"]'
    setting_icon_xpath = '//button[@title="Show list of columns"] | //*[@data-name="IconSettings3"]'
    asset_setting_name_xpath = '//*[@data-id="asset"]'
    source_setting_name_xpath = '//*[@data-id="source"]//*[text()="Source"]'
    maintenance_type_setting_name_xpath = '//*[@data-id="maintenanceType"]'
    categories_setting_name_xpath = '//*[@data-id="categories"]'
    severity_setting_name_xpath = '//*[@data-id="severity"]'
    triggered_date_setting_name_xpath = '//*[@data-id="triggeredDateTime"]'
    status_setting_name_xpath = '//*[@data-id="status"]'
    description_setting_name_xpath = '//*[@data-id="description"]'
    is_overdue_setting_name_xpath = '//*[@data-id="isOverdue"]'
    current_odometer_setting_name_xpath = '//*[@data-id="currentOdometer"]'
    service_due_on_odometer_setting_name_xpath = '//*[@data-id="serviceDueOnOdometer"]'
    service_due_on_engine_hours_setting_name_xpath = '//*[@data-id="serviceDueOnEngineHours"]'
    current_engine_hours_setting_name_xpath = '//*[@data-id="currentEngineHours"]'
    due_on_date_setting_name_xpath = '//*[@data-id="dueOnDate"]'
    service_due_in_kilometers_setting_name_xpath = '//*[@data-id="serviceDueInKilometers"]'
    service_due_in_miles_setting_name_xpath = '//*[@data-id="serviceDueInMiles"]'
    service_due_in_hours_setting_name_xpath = '//*[@data-id="serviceDueInEngineHours"]'
    last_engine_hours_setting_name_xpath = '//*[@data-id="lastEngineHours"]'
    last_maintenance_date_setting_name_xpath = '//*[@data-id="lastMaintenanceDate"]'
    last_odometer_setting_name_xpath = '//*[@data-id="lastOdometer"]'
    expiration_date_setting_name_xpath = '//*[@data-id="expirationDate"]'
    bulk_upload_button_xpath = '//a[@title="Bulk upload"]'
    work_order_xpath = '//*[@id="addWorkOrderMenu"]'
    open_dropdown_value_xpath = '//span[text()="Open"]'
    assigned_dropdown_value_xpath = '//span[text()="Assigned"]'
    in_progress_dropdown_value_xpath = '//span[text()="In progress"]'
    on_hold_dropdown_value_xpath = '//span[text()="On hold"]'
    completed_dropdown_value_xpath = '//span[text()="Completed"]'
    canceled_dropdown_value_xpath = '//span[text()="Canceled"]'
    clear_dropdown_value_xpath = '//*[@title="Clear"]'
    cancel_dropdown_value_xpath = '//*[@title="Cancel"]'
    apply_dropdown_value_xpath = '//*[@title="Apply"]'
    order_reference_column_name_xpath = '//div[text()="Order reference"]'
    date_started_column_name_xpath = '//*[text()="Date started"]'
    date_created_column_name_xpath = '//div[text()="Date created"]'
    date_completed_column_name_xpath = '//div[text()="Date completed"]'
    priority_column_name_xpath = '//div[text()="Priority"]'
    asset_setting_name_in_order_page_xpath = '//*[@data-id="assetName"]'
    order_reference_setting_name_xpath = '//*[@data-id="reference"]'
    date_created_setting_name_xpath = '//*[@data-id="dateTime"]'
    date_completed_setting_name_xpath = '//*[@data-id="completedDateTime"]'
    priority_setting_name_xpath = '//*[@data-id="priorityCode"]'
    status_setting_name_order_page_xpath = '//*[@data-id="statusCode"]'
    engine_hours_reading_setting_name_xpath = '//*[@data-id="engineHoursReading"]'
    odometer_setting_name_xpath = '//*[@data-id="odometerReading"]'
    assigned_to_setting_name_xpath = '//*[@data-id="assignedTo"]'
    get_due_on_date_setting_name_order_page_xpath = '//*[@data-id="dueOnDate"]'
    labor_costs_setting_name_xpath = '//*[@data-id="laborCost"]'
    notes_setting_name_xpath = '//*[@data-id="notes"]'
    opened_by_setting_name_xpath = '//*[@data-id="openedByUser"]'
    parts_cost_setting_name_xpath = '//*[@data-id="partsCost"]'
    reason_for_repair_setting_name_xpath = '//*[@data-id="repairReason"]'
    get_repair_class_setting_name_xpath = '//*[@data-id="repairClass"]'
    shipping_cost_setting_name_xpath = '//*[@data-id="shippingCost"]'
    tax_cost_setting_name_xpath = '//*[@data-id="taxCost"]'
    total_cost_setting_name_xpath = '//*[@data-id="totalCost"]'
    last_updated_setting_name_xpath = '//*[@data-id="lastUpdatedDate"]'
    repair_site_setting_name_xpath = '//*[@data-id="zone"]'
    job_count_setting_name_xpath = '//*[@data-id="jobCount"]'
    reset_setting_name_xpath = '//*[text()="Reset"]'
    status_filter_option_xpath = '//*[normalize-space(text())="Status"]'
    date_created_filter_option_xpath = '//*[normalize-space(text())="Date created"]'
    references_filter_option_xpath = '//*[normalize-space(text())="References"]'
    priority_filter_option_xpath = '//*[normalize-space(text())="Priority"]'
    status_drop_down_xpath = '(//*[@aria-label="Status"]//button)[2]'
    applied_status_text_xpath = '//*[@placeholder="Open"]'
    open_status_xpath = '//div[contains(@class, "zen-checkbox-list-with-action__label-text")]//span[normalize-space(.)="Open"]'
    select_date_button_xpath = '//*[text()="Date range"]'
    date_created_header_xpath = '//*[@class="zen-side-panel-cell__title" and normalize-space(text())="Date created"]'
    today_option_xpath = '//*[text()="Today"]'
    applied_today_filter_xpath = '//*[text()="Today"]'
    priority_low_xpath = '//label[.//span[normalize-space(.)="Low"]]'
    priority_medium_xpath = '//*[text()="Medium"]'
    priority_high_xpath = '//*[text()="High"]'
    priority_critical_xpath = '//*[text()="Critical"]'
    priority_low_checkbox_checked_xpath = '//*[@data-name="CheckboxIconCheckmark"]'
    date_filter_jobs_page_xpath = '//*[contains(@class, "zen-date-range")]'
    select_all_dropdown_value_xpath = '//*[text()="Select all"]'
    date_completed_text_xpath = '//div[@role="dialog"]//*[text()="Date completed"]'
    today_text_xpath = '//*[text()="Today"]'
    yesterday_text_xpath = '//*[text()="Yesterday"]'
    this_week_text_xpath = '//*[text()="This week"]'
    last_week_text_xpath = '//*[text()="Last week"]'
    this_month_text_xpath = '//div[text()="This month"]'
    last_month_text_xpath = '//div[text()="Last month"]'
    last_3_months_text_xpath = '//div[text()="Last 3 months"]'
    custom_text_xpath = '//div[text()="Custom"]'
    clear_button_disabled_xpath = '//*[text()="Clear" and @disabled]'
    asset_setting_name_in_jobs_page_xpath = '//*[@data-id="assetName"]'
    order_reference_setting_name_in_jobs_page_xpath = '//*[@data-id="reference"]'
    source_setting_name_in_jobs_page_xpath = '//*[@data-id="source"]'
    maintenance_type_setting_name_in_jobs_page_xpath = '//*[@data-id="maintenanceType"]'
    categories_setting_name_in_jobs_page_xpath = '//*[@data-id="categories"]'
    status_setting_name_in_jobs_page_xpath = '//*[@data-id="statusCode"]'
    date_started_setting_name_xpath = '//*[@data-id="startDate"]'
    date_completed_setting_name_in_jobs_page_xpath = '//*[@data-id="dateCompleted"]'
    date_created_setting_name_in_jobs_page_xpath = '//*[@data-id="dateTime"]'
    triggered_date_setting_name_in_jobs_page_xpath = '//*[@data-id="triggeredDate"]'
    engine_hours_reading_setting_name_in_jobs_page_xpath = '//*[@data-id="engineHoursReading"]'
    odometer_reading_setting_name_in_jobs_page_xpath = '//*[@data-id="odometerReading"]'
    hours_setting_name_xpath = '//*[@data-id="hours"]'
    labor_costs_setting_name_in_jobs_page_xpath = '//*[@data-id="laborCosts"]'
    parts_cost_setting_name_in_jobs_page_xpath = '//*[@data-id="partsCost"]'
    shipping_cost_setting_name_in_jobs_page_xpath = '//*[@data-id="shippingCosts"]'
    tax_cost_setting_name_in_jobs_page_xpath = '//*[@data-id="taxes"]'
    total_cost_setting_name_in_jobs_page_xpath = '//*[@data-id="totalCost"]'
    priority_setting_name_in_jobs_page_xpath = '//*[@data-id="severity"]'
    reset_setting_name_in_jobs_page_xpath = '//*[text()="Reset"]'
    schedule_button_xpath = '//span[text()="Schedule"]'
    search_filter_xpath = '//*[@placeholder="Search"]'
    frequency_filter_xpath = '//*[@placeholder="Frequency"]'
    repeats_filter_xpath = '//*[@placeholder="Repeats"]'
    name_column_text_xpath = '//div[text()="Name"]'
    categories_column_text_xpath = '//div[text()="Categories"]'
    repeats_column_text_xpath = '//div[text()="Repeats"]'
    frequency_column_text_xpath = '//div[text()="Frequency"]'
    assets_added_column_text_xpath = '//div[text()="Assets added"]'
    frequency_based_on_distance_text_xpath = '//*[text()="Frequency based on distance"]'
    frequency_based_on_months_text_xpath = '//*[text()="Frequency based on months"]'
    frequency_based_on_weeks_text_xpath = '//*[text()="Frequency based on weeks"]'
    frequency_based_on_days_text_xpath = '//*[text()="Frequency based on days"]'
    frequency_based_on_engine_hours_text_xpath = '//*[text()="Frequency based on engine hours"]'
    yes_option_text_xpath = '//div[text()="Yes"]'
    no_option_text_xpath = '//div[text()="No"]'
    name_setting_text_xpath = '//*[@id="name"]'
    categories_setting_text_xpath = '//*[@id="categories"]'
    repeats_setting_text_xpath = '//*[@id="repeats"]'
    frequency_setting_text_xpath = '//*[@id="frequency"]'
    assets_added_setting_text_xpath = '//*[@id="assetsAdded"]'
    days_setting_text_xpath = '//*[@id="days"]'
    weeks_setting_text_xpath = '//*[@id="weeks"]'
    months_setting_text_xpath = '//*[@id="months"]'
    day_of_week_setting_text_xpath = '//*[@id="dayOfWeek"]'
    day_of_month_setting_text_xpath = '//*[@id="dayOfMonth"]'
    engine_hours_setting_text_xpath = '//*[@id="engineHours"]'
    distance_setting_text_xpath = '//*[@id="distance"]'
    event_date_setting_text_xpath = '//*[@id="eventDate"]'
    source_setting_text_xpath = '//*[@id="source"]'
    filters_pop_up_title_xpath = '//div[text()="All Filters"]'
    groups_filter_option_xpath = '//div[text()="Groups"]'
    apply_button_xpath = '//*[@class="zen-groups-filter-menu__button-group"]/button[2]'
    assets_filter_option_xpath = '//div[text()="Assets"]'
    include_archived_data_filter_option_xpath = '//div[text()="Include archived (historical) data"]'
    maintenance_types_filter_option_xpath = '//div[text()="Maintenance types"]'
    sources_filter_option_xpath = '//div[text()="Sources"]'
    severity_filter_option_xpath = '//div[text()="Severity"]'
    show_snoozed_requests_filter_option_xpath = '//div[text()="Show snoozed requests"]'
    group_filter_in_filter_pop_up_xpath = '(//*[contains(@class, "groups-filter") and @title="Open filter"])[2]'
    asset_information_check_box_xpath = '//*[@title="Toggle Company group/Asset Information filter"]/div'
    close_group_drop_down_xpath = '(//*[contains(@class, "groups-filter") and @title="Open filter"])[2]'
    selected_group_in_group_filter_xpath = '//*[@placeholder="Asset Information"]'
    assets_filter_in_filter_pop_up_xpath = '(//*[@aria-label="Assets"])[2]'
    asset_check_box_xpath = '(//*[@aria-label="Assets"]//*[@type="checkbox"])[1]'
    asset_drop_down_xpath = '(//*[@aria-label="Assets"]/button)[2]'
    selected_asset_filter_in_filters_pop_up_xpath = '//div[normalize-space(text())="Selected:"]'
    maintenance_filter_in_filter_pop_up_xpath = '//*[@aria-label="Maintenance types"]//input'
    maintenance_check_box_xpath = '//*[@aria-label="Maintenance types"]//*[@type="checkbox"]'
    maintenance_drop_down_xpath = '//*[@aria-label="Maintenance types"]/button'
    sources_filter_in_filter_pop_up_xpath = '//*[@placeholder="Sources"]'
    select_all_checkbox_xpath = '//*[text()="Select all"]'
    manual_checkbox_xpath = '//*[text()="Manual"]'
    data_insight_checkbox_xpath = '//*[text()="Data insight"]'
    scheduled_checkbox_xpath = '//*[text()="Scheduled"]'
    driver_reported_checkbox_xpath = '//*[text()="Driver reported"]'
    faults_checkbox_xpath = '//*[text()="Faults"]'
    sources_drop_down_xpath = '//*[@aria-label="Sources"]/button'
    manual_filter_applied_xpath = '//*[@placeholder="Manual"]'
    severity_dropdown_xpath = '//*[@aria-label="Severity"]/button'
    select_all_severity_xpath = '//*[text()="Select all"]'
    unknown_severity_xpath = '//*[text()="Unknown"]'
    low_severity_xpath = '//*[text()="Low"]'
    medium_severity_xpath = '//*[text()="Medium"]'
    high_severity_xpath = '//*[text()="High"]'
    critical_severity_xpath = '//*[text()="Critical"]'
    high_severity_option_xpath = '//*[text()="High"]'
    applied_severity_filter_xpath = '//*[@placeholder="High"]'
    close_button_xpath = '//*[@aria-label="All Filters"]//*[@aria-label="Close"]'
    search_bar_xpath = '//*[@placeholder="Search"]'
    defect_lists_xpath = '//*[@class="geo-header__button-container"]//*[text()="Defect Lists"]'
    report_button_xpath = '//*[@class="geo-header__button-container"]//button[@title="Reports"]'
    inspection_button_xpath = '//*[contains(@class,"geo-header__button-container")]//*[@title="Add Asset Inspection log"]'
    sort_by_asset_xpath = '//span[@class="sort-constructor_labels geo-caption__content "]'
    sort_by_asset_drop_down_xpath = '//*[@title="Sort by"]'
    linked_assets_title_xpath = '//*[@aria-label="Linked assets"]'
    asset_option_text_xpath = '//button[text()="Asset"]'
    date_option_text_xpath = '//button[text()="Date"]'
    duration_option_text_xpath = '//button[text()="Duration"]'
    settings_icon_in_asset_inspection_xpath = '//*[@title="Show or hide columns"]'
    reset_to_default_text_xpath = '//*[text()="Reset to default"]'
    date_and_time_text_xpath = '//*[text()="Date & Time"]'
    asset_name_text_xpath = '//*[text()="Asset Name"]'
    driver_text_xpath = '//*[text()="Driver"]'
    status_text_xpath = '//*[text()="Status"]'
    defects_text_xpath = '//*[text()="Defects"]'
    comments_text_xpath = '//*[text()="Comments"]'
    inspection_type_text_xpath = '//*[text()="Inspection Type"]'
    asset_type_text_xpath = '//*[text()="Asset Type"]'
    certification_text_xpath = '//*[text()="Certification"]'
    duration_text_xpath = '//div[text()="Duration"]'
    filter_button_xpath = '//*[@id="engineFaults_OptionsButtonId" or @id="engineMeasurements_OptionsButtonId"]'
    sort_by_fault_code_xpath = '//*[@id="engineFaults_SortsId"]'
    sort_by_fault_code_drop_down_xpath = '//*[@id="engineFaults_SortsId"]//button[2]'
    report_button_in_fault__xpath = '//*[@id="engineFaults_reports"]'
    dismiss_faults_button_xpath = '//*[@id="faults_dismissId"]'
    columns_button_xpath = '//*[@id="engineFaults_editColumns"]'
    fault_code_option_text_xpath = '//button[text()="Fault Code"]'
    description_option_text_xpath = '//button[text()="Description"]'
    times_logged_option_text_xpath = '//button[text()="Times Logged"]'
    source_option_text_xpath = '//button[text()="Source"]'
    severity_option_text_xpath = '//button[text()="Severity"]'
    fault_code_text_xpath = '//div[text()="Fault Code"]'
    description_text_xpath = '//div[text()="Description"]'
    current_status_text_xpath = '//div[text()="Current Status"]'
    times_logged_text_xpath = '//div[text()="Times Logged"]'
    source_text_xpath = '//div[text()="Source"]'
    protocol_text_xpath = '//div[text()="Protocol"]'
    advanced_details_text_xpath = '//div[text()="Advanced Details"]'
    selection_text_xpath = '//div[text()="Selection"]'
    severity_text_xpath = '//div[text()="Severity"]'
    controller_text_xpath = '//div[text()="Controller"]'
    group_by_diagnostic_xpath = '//*[@id="groupBy_DropdownId"]'
    report_button_measurement_page_xpath = '//*[@id="engineMeasurements_reports"]'
    group_by_diagnostic_dropdown_xpath = '//*[@id="groupBy_DropdownId"]//button[2]'
    diagnostic_option_text_xpath = '//button[text()="Diagnostic"]'
    speed_profile_header_xpath = '//span[text()="Speed Profile"]'
    filter_button_in_speed_profile_xpath = '//*[@id="speedProfile_OptionButtonId"]'
    view_trips_button_xpath = '//*[@id="speedProfile_ViewTripsButtonId"]'
    log_data_and_collisions_header_xpath = '//*[@class="geo-header__page-name-part"]//h1[text()="Log Data and Collisions"]'
    reports_button_log_data_and_collisions_xpath = '//button[@title="Reports"]'
    search_bar_log_data_and_collisions_xpath = '//input[@id="logDetails_searchId"]'
    filters_menu_xpath = '//*[contains(@class,"geo-page-toolbar")]//*[@id="logDetails_OptionButtonId"]'
    apply_changes_button_xpath = '//*[text()="Apply changes"]'
    sort_by_vehicle_and_date_time_xpath = '//*[@id="logDetails_SortButtonSet"]'
    sort_by_vehicle_and_date_time_dropdown_xpath = '//*[@id="logDetails_SortButtonSet"]//button[2]'
    vehicle_and_date_time_option_text_xpath = '//button[text()="Vehicle and date/time"]'
    reason_and_date_time_option_text_xpath = '//button[text()="Reason and date/time"]'
    record_type_and_date_time_option_text_xpath = '//button[text()="Record type and date/time"]'


    # Sustainability pages
    sustainabilityoverview_header_xpath = '//*[contains(@class, "page-header")]//*[text()="Sustainability Overview"]'
    mfuel_and_ev_energyusage_header_xpath = '//*[@class="geo-header"]//*[text()="Fuel and EV Energy Usage"]'
    ev_batteryhealth_header_xpath = '//*[@class="geo-page-header"]//*[text()="EV Battery Health"]'
    ev_charginghistory_header_xpath = '//*[@class="geo-page-header"]//*[text()="EV Charging History"]'
    bev_rangecapability_header_xpath = '//*[@class="geo-page-header"]//*[text()="BEV Range Capability"]'
    powertrain_fuel_types_xpath = '//*[@placeholder="Powertrain and fuel types"]'
    last_3months_date_field_xpath = '//*[contains(text() , "Last 3 months")]'
    emission_intensity_xpath = '(//*[text()="Emissions Intensity"])[1]'
    tailpipe_emissions_avoided_xpath = '(//*[text()="Tailpipe Emissions Avoided"])[1]'
    fuel_energy_economy_xpath = '(//*[text()="Fuel and Energy Economy"])[1]'
    ev_charging_history_xpath = '(//*[text()="EV Charging History"])[1]'
    fill_up_xpath = '(//*[@aria-label="Fill-Ups"])[1]'


    # Reports pages
    myreports_header_xpath = '//*[@class="geotab-page"]//*[text()="My Reports"]'
    report_setup_header_xpath = '//*[@id="page-title"]//*[text()="Report Setup"]'
    type_xpath = '//*[@title="Type"]'
    custom_report_id = 'customReports_add'
    custom_report_xpath = '(//*[@id="customReports_add"])[1]'
    custom_report_text_xpath = '(//*[text()="Custom report"])[1]'
    custom_report_title_xpath = '//*[text()="CUSTOM REPORTS"]'
    upload_file_xpath = '//*[text()="Drop your file here to upload, or browse your computer."]'
    inputfile_xpath = '//*[@class="uploadFileElement"]'
    email_report_tab_id = 'customReport_email'
    savereport_id = 'customReport_save'
    upload_file_in_configure_report_xpath = '//*[@class="geo-drag-and-drop-uploader__icon"]'
    email_options_on_xpath = '//label[normalize-space(text())="Email options"]/following::label[normalize-space(text())="On"][1]'
    select_groups_xpath = '(//*[@placeholder="Select groups"])[3]'
    select_users_xpath = '//label[normalize-space(text())="Individual recipients list"]/following::input[@placeholder="Select users…"][1]'
    refresh_period_xpath = '//label[normalize-space(.)="Refresh period"]/following-sibling::select'
    every_30min_period_xpath = '//label[normalize-space(.)="Refresh period"]/following-sibling::select/option[normalize-space(.)="Every 30 minutes"]'
    edit_report_name_xpath = '//*[@id="customReports_reportNameField"]'
    email_options_label_xpath = '//*[text()="Email options"]'
    report_name_id = 'customReports_reportName'
    user_input_xpath = '//input[contains(@class, "geo-secondary-button-with-expand__input")]'
    remove_report_button_id = 'customReport_remove'
    remove_report_confirmation_button_xpath = '//*[contains(@class, "dialogConfirmed") and text()="Remove"]'
    next_run_xpath1 = '//div[@class="nextRun geo-view-list__container"]//input[@class="geo-text-input hasDatePicker geo-view-list__field"]'
    now_button_xpath = '//button[normalize-space(text())="Now"]'
    done_button_xpath = '//button[normalize-space(text())="Done"]'

    # Rules and Exceptions pages
    rules_header_xpath = '//*[@class="geo-page-header"]//*[text()="Rules"]'
    safetysection_id = 'section-safetyHeader'
    addrules_id = 'rules_addId'
    reprocessdata_id = 'rules_reprocessDataButton'
    notification_template_id = 'rules_notificationTemplates'
    distribution_lists_id = 'rules_advancedButton'
    exception_rule_edit_header_xpath = '//*[text()="Exception Rule Edit"]'
    save_button_id = 'rule_Save'
    cancel_button_id = 'rule_cancelId'
    back_button_xpath = '//*[@aria-label="Back to rules list"]'
    name_tab_id = 'rule_tabDefinition'
    condition_tab_id = 'rule_tabConditions'
    notifications_tab_id = 'rule_tabNotifications'
    media_tab_id = 'rule_tabMedia'
    comment_id = 'rule_commentId'
    exceptions_header_xpath = '//*[@class="geo-page-header"]//*[text()="Exceptions"]'
    color_xpaths = [
        '//*[@title="Select red color"]',
        '//*[@title="Select orange color"]',
        '//*[@title="Select green color"]',
        '//*[@title="Select yellow color"]',
        '//*[@title="Select lightBlue color"]',
        '//*[@title="Select blue color"]',
        '//*[@title="Select purple color"]' ]
    name_field_xpath = '//label[text()="Name"]'
    color_field_xpath = '//label[text()="Color"]'
    publish_to_groups_field_xpath = '//label[text()="Publish to groups"]'
    comment_field_xpath = '//label[text()="Comment"]'
    publish_to_groups_field_open_drop_down_xpath = '//button[@title="Open filter"]'
    publish_to_groups_field_close_drop_down_xpath = '//button[@title="Close filter"]'
    publish_to_groups_input_box_xpath = '//*[@placeholder="Select groups"]'
    first_group_in_dropdown_xpath = '//button//span[text()="Asset Information"]'
    select_all_xpath = '//*[@title="All in Asset Information"]'
    first_group_list_xpath = '//span[text()="Asset Information"]'
    cross_mark_next_to_selected_group_xpath = '//*[@title="Remove selection"]'
    condition_header_xpath = '//legend[text()="Conditions"]'
    engine_data_condition_xpath = '//button[text()="Engine data"]'
    active_fault_option_text_xpath = '//label[text()="Active Fault"]'
    any_fault_option_text_xpath = '//*[text()="Any Fault"]'
    measurement_or_data_option_text_xpath = '//*[text()="Measurement or Data"]'
    engine_data_header_in_engine_data_condition_id = 'conditionsBuilder_adder_title'
    type_field_in_engine_data_condition_xpath = '//*[@id="conditionsBuilder_engineDiagnosticBuilder"]//label[text()="Type"]'
    diagnostic_field_in_engine_data_condition_xpath = '//*[text()=" Diagnostic "]/parent::span'
    add_a_condition_field_in_engine_data_condition_xpath = '//*[@placeholder="Add a condition..."]'
    display_all_diagnostic_field_in_engine_data_condition_xpath = '//*[@id="conditionsBuilder_engineDiagnostic_showAllDiagnostic"]'
    zone_or_zone_type_textbox_xpath = '//*[text()="Zone or zone type"]'
    zone_header_in_zone_condition_xpath = '//*[@id="conditionsBuilder_adder_title" and text()="Zone"]'
    type_option_text_xpath = '//*[@title="Add Engine Condition"]//*[text()="Type"]'
    zone_option_text_xpath = '//*[@id="conditionsBuilder_zone_zoneField"]/label'
    event_option_text_xpath = '//label[text()="Event"]'
    entering_option_text_xpath = '//*[text()="Entering"]'
    exiting_option_text_xpath = '//*[text()="Exiting"]'
    outside_option_text_xpath = '//*[text()="Outside"]'
    inside_option_text_xpath = '//*[text()="Inside"]'
    add_button_xpath = '//*[text()="Add"]'
    roads_with_speed_limit_textbox_xpath = '//button[text()="Roads with speed limit"]'
    roads_with_speed_limit_dialog_box_xpath = '//*[@id="conditionsBuilder_adder_title"]'
    over_option_text_xpath = '//label[@class="geo-switcher__label" and text()="Over"]'
    under_option_text_xpath = '//label[@class="geo-switcher__label" and text()="Under"]'
    empty_text_box_under_over_and_under_xpath = '//*[@id="conditionsBuilder_roadBuilder_distanceInput"]'
    speed_textbox_xpath = '//*[@value="Speed"]'
    speed_dialog_box_xpath = '//*[@id="conditionsBuilder_adder_title"]'
    speed_limit_textbox_xpath = '//*[@value="SpeedLimit"]'
    speed_limit_dialog_box_xpath = '//*[@id="conditionsBuilder_adder_title"]'
    truck_speed_limit_field_xpath = '//*[text()="Truck speed limit"]'
    yes_button_xpath = '//*[@class="geo-switcher__label" and text()="Yes"]'
    no_button_xpath = '//*[@class="geo-switcher__label" and text()="No"]'
    over_the_limit_by_field_xpath = '//*[text()="Over the limit by"]'
    exclude_estimated_speed_limits_field_xpath = '//*[text()="Exclude estimated speed limits"]'
    on_button_xpath = '//*[@class="geo-switcher__label" and text()="On"]'
    off_button_xpath = '//*[@class="geo-switcher__label" and text()="Off"]'
    more_dropdown_xpath = '//*[@data-popup-id="conditionsBuilder_moreConditions"]'
    device_header_text_xpath = '//legend[text()="Device"]'
    ignition_option_text_xpath = "//button[@value='Ignition']"
    driver_option_text_xpath = "//button[@value='Driver']"
    group_option_text_xpath = "//button[@value='Group']"
    asset_inspection_defect_option_text_xpath = "//button[@value='DVIRDefect']"

    # Trip
    trip_header_text_xpath = "//legend[text()='Trip']"
    driving_option_text_xpath = "//button[@value='IsDriving']"
    stop_option_text_xpath = "//button[@value='Stop']"
    trip_distance_option_text_xpath = "//button[@value='TripDistance']"
    trip_duration_option_text_xpath = "//button[@value='TripDuration']"

    # Auxiliaries
    auxiliaries_header_text_xpath = "//legend[text()='Auxiliaries']"
    aux_1_option_text_xpath = "//button[@value='Aux1']"
    aux_2_option_text_xpath = "//button[@value='Aux2']"
    aux_3_option_text_xpath = "//button[@value='Aux3']"
    aux_4_option_text_xpath = "//button[@value='Aux4']"
    aux_5_option_text_xpath = "//button[@value='Aux5']"
    aux_6_option_text_xpath = "//button[@value='Aux6']"
    aux_7_option_text_xpath = "//button[@value='Aux7']"
    aux_8_option_text_xpath = "//button[@value='Aux8']"

    # Work Hours
    work_hours_header_text_xpath = "//legend[text()='Work Hours']"
    after_work_hours_rule_option_text_xpath = "//button[@value='AfterRuleWorkHours']"
    work_hours_rule_option_text_xpath = "//button[@value='RuleWorkHours']"
    after_work_hours_device_option_text_xpath = "//button[@value='AfterDeviceWorkHours']"
    device_work_hours_option_text_xpath = "//button[@value='DeviceWorkHours']"

    # Wrappers
    wrappers_header_text_xpath = "//legend[text()='Wrappers']"
    is_value_more_than_option_text_xpath = "//button[@value='IsValueMoreThan']"
    is_value_less_than_option_text_xpath = "//button[@value='IsValueLessThan']"
    is_value_equal_to_option_text_xpath = "//button[@value='IsValueEqualTo']"

    # Logic
    logic_header_text_xpath = "//legend[text()='Logic']"
    and_option_text_xpath = "//button[@value='And']"
    or_option_text_xpath = "//button[@value='Or']"

    notifications_tab_xpath = '//*[@id="rule_tabNotifications"]'
    notifications_recipients_header_xpath = '//*[text()="Notification Recipients"]'
    add_email_option_xpath = '//button[@value="Email"]'
    add_alert_option_xpath = '//span[text()="Add alert"]'
    add_driver_feedback_option_xpath = '//span[text()="Add driver feedback"]'
    more_option_xpath = '//*[contains(@class, "ruleNotifier_advancedOptionsButton")]'
    help_section_xpath = '//legend[text()="Help"]'
    summary_in_help_section_xpath = '//p[@class="helper-text-01"]'
    template_field_xpath = '//label[text()="Template"]'
    email_field_xpath = '//label[text()="Email"]'
    template_dropdown_xpath = '//select[contains(@class, "ruleNotifier_optionsInput")]'
    default_email_template_option_text_xpath = '//*[@value="EmailTemplateDefaultExceptionRuleId"]'
    add_new_template_option_text_xpath = '//*[@value="Add new template"]'
    warning_popup_xpath = '//*[contains(text(), "re about to leave the page.")]'
    email_textbox_xpath = '//input[@placeholder="Type here and press Add when done..."]'
    email_dropdown_xpath = '//ul[contains(@class,"geo-autocomplete")]'
    add_alert_dropdown_xpath = '//span[text()="Add alert"]'
    popup_option_text_xpath = '//span[text()="Popup"]'
    popup_description_xpath = '//span[contains(text(),"yellow, low-priority popup alert")]'
    urgent_popup_option_text_xpath = '//span[text()="Urgent popup"]'
    urgent_popup_description_xpath = '//span[contains(text(),"Display a red popup")]'
    log_only_option_text_xpath = '//span[text()="Log only"]'
    log_only_description_xpath = '//span[contains(text(),\'Log a notification in "My Notifications"\')]'

    # --- Add Driver Feedback Dropdown ---
    add_driver_feedback_dropdown_xpath = '//span[text()="Add driver feedback"]'
    beep_three_times_option_text_xpath = '//span[text()="Beep three times"]'
    beep_three_times_description_xpath = '//span[text()="Beep the device three times"]'
    beep_three_times_rapidly_option_text_xpath = '//span[text()="Beep three times rapidly"]'
    beep_three_times_rapidly_description_xpath = '//span[text()="Rapidly beep the device three times"]'
    beep_ten_times_rapidly_option_text_xpath = '//span[text()="Beep ten times rapidly"]'
    beep_ten_times_rapidly_description_xpath = '//span[text()="Rapidly beep the device ten times"]'
    text_message_option_text_xpath = '//span[text()="Text message"]'
    text_message_description_xpath = '//span[contains(text(),"Send a text notification")]'
    go_talk_option_text_xpath = '//span[text()="GO TALK"]'
    go_talk_description_xpath = '//span[contains(text(),"requires an IOX-GOTALK")]'
    change_status_option_text_xpath = '//span[text()="Change status"]'
    change_status_description_xpath = '//span[contains(text(),"Prompt the driver to change their status")]'

    # --- More Options Dropdown ---
    more_options_dropdown_xpath = '//*[contains(@class, "ruleNotifier_advancedOptionsButton")]'
    web_request_option_text_xpath = '//span[text()="Web request"]'
    web_request_description_xpath = '//span[text()="Make an HTTP GET or POST web request."]'
    assign_to_group_option_text_xpath = '//span[text()="Assign to group"]'
    assign_to_group_description_xpath = '//span[text()="Assign asset to specified group."]'
    email_to_group_option_text_xpath = '//span[text()="Email to group"]'
    email_to_group_description_xpath = '//span[text()="Email to users in selected group"]'
    distribution_list_option_text_xpath = '//span[text()="Distribution list"]'
    distribution_list_description_xpath = '//span[text()="Send notification to distribution list"]'
    assign_as_personal_business_option_text_xpath = '//span[text()="Assign as Personal/Business"]'
    assign_as_personal_business_description_xpath = '//span[contains(text(),"Personal Mode") or contains(text(),"Business Mode")]'
    media_upload_tab_xpath = '//*[@id="rule_tabMedia"]'
    media_upload_settings_header_xpath = '//*[text()="Media Upload Settings"]'
    media_type_field_xpath = '//*[contains(text(), "Media type")]'
    information_symbol_xpath = '//*[@id="Custommedia-upload_mediaTypeTooltip"]'
    information_symbol_message_xpath = '//*[@data-tooltip="The type of media uploaded when a rule is triggered."]'
    video_button_xpath = '//*[contains(text(), " Video")]'
    snapshot_button_xpath = '//*[contains(text(), " Snapshot")]'
    none_button_xpath = '//*[contains(text(), " None")]'

    # --- Cancel button in Exception Rule Edit page ---
    cancel_button_xpath = '//*[@id="rule_cancelId"]'

    # --- Notification Templates ---
    notification_template_button_xpath = '//*[text()="Notification templates"]'
    notification_templates_header_xpath = '//h1[text()="Notification Templates"]'
    search_option_xpath = '//*[@id="notificationTemplates_SearchId"]'
    sort_by_name_option_xpath = '//*[@id="notificationTemplates_SortToolbarId"]'
    add_email_template_option_xpath = '//a[text()="Add email template"]'
    add_web_template_option_xpath = '//a[text()="Add web template"]'
    add_text_template_option_xpath = '//a[text()="Add text template"]'

    # --- Add Email Template ---
    add_email_template_button_xpath = '//a[text()="Add email template"]'
    email_template_edit_header_xpath = '//h1[contains(normalize-space(.), "Email Template")]'
    subject_field_xpath = '//label[text()="Subject"]'
    body_field_xpath = '//label[text()="Body"]'
    exception_report_field_xpath = '//label[text()="Exception report"]'

    # --- Exceptions Detail Report Dropdown ---
    do_not_attach_exceptions_detail_report_dropdown_xpath = '//*[@id="notificationTemplateEmail_ExceptionsDetailTemplates"]'
    do_not_attach_exceptions_detail_report_option_text_xpath = '//*[@value="no"]'
    default_exceptions_detail_report_option_text_xpath = '//*[@value="ReportTemplateExceptionsDetailId"]'
    possible_collisions_option_text_xpath = '//*[@value="ReportTemplatePossibleCollisionsId"]'
    advanced_exceptions_detail_report_option_text_xpath = '//*[@value="ReportTemplateAdvancedExceptionsDetailId"]'
    cancel_button_in_email_template_edit_page_xpath = '//*[@id="notificationTemplateEmail_CancelButtonId"]'
    add_web_template_button_xpath = '//a[text()="Add web template"]'

    # --- Web Request Template Edit Page ---
    web_request_template_edit_header_xpath = '//h1[contains(normalize-space(.), "Web Request Template")]'
    template_name_field_xpath = '//*[text()="Template name:"]'
    url_field_xpath = '//*[text()="URL:"]'
    http_request_type_field_xpath = '//*[text()="HTTP request type:"]'
    available_tokens_section_xpath = '//*[text()="Available Tokens"]'

    # --- HTTP Request Type Buttons ---
    get_button_xpath = '//label[text()="GET"]'
    post_button_xpath = '//label[text()="POST"]'

    # Messages page
    message_header_xpath = '//*[@class="geo-header"]//*[text()="Messages"]'
    new_message_xpath = '//*[@title="Message"]'
    assets_tab_id = 'messages_tabVehicles'
    users_tab_id = 'messages_tabDrivers'
    message_button_xpath = '//*[@aria-label="Message"]'
    new_message_popup_header_title_xpath = '//*[text()="New message"]'
    new_message_popup_description_xpath = '//*[text()="Messages can be sent to multiple assets and users. Select all that apply. Replies are only visible to you."]'
    search_filter_in_message_popup_xpath = '//*[@aria-label="Search for asset or user"]'
    compose_message_button_disabled_xpath = '//*[@id="messages_rightPane"]/div/div[2]/div[2]/div/div[1]/button[@disabled]'
    assets_subtab_xpath = '//*[@id="recipients_devicesTab"]'
    assets_list_with_checkboxes_xpath = '//*[@id="recipients_devicesList"]'
    users_subtab_in_message_popup_xpath = '//*[@id="recipients_usersTab"]'
    users_list_with_checkboxes_xpath = '//*[@data-tabs-panel="recipients_usersList"]'
    first_user_in_users_list_xpath = '(//*[@class="geo-checkbox__box"])[7]'
    compose_message_button_xpath = '//*[@class="geo-button geo-button--action messages-recipients-pane__compose-button"]'
    back_to_asset_selection_xpath = '//*[@class="geo-button toolbar__back messages-header__back toolbar__back--hidden"]'
    user_name_xpath = '//*[@class="messages-header__recipients ellipsis"]'
    search_icon_xpath = '//*[@aria-label="Search messages in chat"]'
    cross_mark_symbol_xpath = '//*[@aria-label="Close chat"]'


    # Notifications page
    notifications_header_xpath = '//*[@id="notifications-header"]//*[text()="Notifications"]'
    notifications_types_xpath = '//*[text()="Notification types"]'
    reload_id = 'reload'

    # Config pages
    # System Settings page
    system_settings_xpath = '//*[@id="systemSettings_PageId_react"]//*[text()="System Settings"]'
    general_id = 'general'
    maps_id = 'maps'
    assets_id = 'assets'
    hos_id = 'hos'
    userAccounts_id = 'userAccounts'
    communications_id = 'communications'
    dataPurge_id = 'dataPurge'
    addIns_xpath = '//button[@id="addIns" and //*[@title="Add-Ins"]]'

    #Work Hours
    work_hours_header_xpath = '//*[@class="geo-header"]//*[text()="Work Hours"]'
    work_hours_search_id = 'workTimes_searchId'
    work_hours_sort_button_id = 'workTimesSortButtonSet'
    total_items_text_id = 'workTimes_total'
    all_hours_text_xpath = '//*[@id="workTimes_BuilderId"]//*[text()="All hours"]'
    early_departure_hours_text_xpath = '//*[@id="workTimes_BuilderId"]//*[text()="Early departure hours"]'
    late_arrival_hours_text_xpath = '//*[@id="workTimes_BuilderId"]//*[text()="Late arrival hours"]'
    lunch_hours_text_xpath = '//*[@id="workTimes_BuilderId"]//*[text()="Lunch hours"]'
    standard_hours_text_xpath = '//*[@id="workTimes_BuilderId"]//*[text()="Standard hours"]'

    #Audit Log
    audit_log_header_xpath = '//*[@class="geo-header"]//*[text()="Audit Log"]'
    audit_log_search_id = 'auditLogs_SearchId'
    options_dropdown_id = 'auditLogs_OptionsDiv'
    user_login_xpath = '(//*[@id="auditLogs_BuilderId"]//*[text()="User login"])[1]'

    # Driver Safety
    due_for_coaching_header_xpath = '//*[text()="Due for Coaching"]'
    assign_driver_header_xpath = '//*[text()="Assign Drivers"]'
    collisions_header_xpath = '//*[text()="Collisions"]'
    fyinotify_header_xpath = '//*[text()="Fyi Notify"]'
    opentasksreport_header_xpath = '//*[text()="Open Tasks Report"]'
    driversreport_header_xpath = '//*[text()="DRIVERS REPORT"]'
    groupreport_header_xpath = '//*[text()="Group Report"]'
    coachesreport_header_xpath = '//*[text()="Coaches Report"]'
    programstatusreport_header_xpath = '//*[text()="Program Status Report"]'
    behaviorsreport_header_xpath = '//*[text()="Behaviors Report"]'
    events_header_xpath = '//*[text()="Events"]'
    coachinghistory_header_xpath = '//*[text()="Coaching History"]'
    recognitionhistory_header_xpath = '//*[text()="Recognition History"]'
    dataexport_header_xpath = '//*[@class="page-header" and text()="Data Export"]'
    search_textbox_xpath = '//*[@placeholder="Search by Event ID"]'

    # Video Search
    vehicles_header_xpath = '//*[@class="filter-header-title" and text()="Vehicles"]'
    map_search_header_xpath = '//*[@class="filter-header-title" and text()="Map Search"]'
    saved_videos_header_xpath = '//*[@class="filter-header-title" and text()="Saved Videos"]'
    video_tags_header_xpath = '//*[@class="filter-header-title" and text()="Video Tags"]'

    # Admin
    users_header_xpath = '//*[@class="filter-header-title" and text()="User Management"]'
    admin_vehicles_header_xpath = '//*[@class="filter-header-title" and text()="Vehicle Management"]'
    telematics_assets_header_xpath = '//*[contains(@class,"geo-header__page")]//*[normalize-space(text())="Assets"]'
    telematics_assets_tab_id = 'inventory_tabAssets'
    telematics_cameras_tab_id = 'inventory_tabVideoDevices'
    linked_assets_xpath = '//*[@aria-label = "Linked assets"]'
    installation_xpath = '//*[@aria-label = "Installation"]'
    asset_reports_button_xpath = '//*[@title = "Reports"]'
    create_assets_button_xpath = '//*[@title = "Assets"]'
    telematics_assets_agreement_xpath = '//*[text()="Geotab End User Agreement"]'
    devices_header_xpath = '//*[@class="filter-header-title" and text()="Device Management"]'
    geofences_header_xpath = '//*[@class="filter-header-title" and text()="Geofence Management"]'
    admin_insights_driver_id_header_xpath = '//*[@class="filter-header-title" and text()="Driver Id Assignment" or text()="Driver ID Assignment"]'
    config_settings_header_xpath = '//*[@class="config-setting__page-header" and text()="Configuration Settings"]'
    safe_driving_report_tab_xpath = '//*[@class="tab-text" and text() = "Safe Driving Report"]'
    setting_header_xpath = '//*[@class="lytx-table-header-cell__content"]//*[text() =" Setting "]'
    group_header_xpath = '//*[@data-test-id="sortable-container-Group"]'
    minimum_distance_driven_header_xpath = '//*[@class="lytx-table-header-cell__content"]//*[text() =" Minimum Distance Driven "]'
    edit_icon_xpath = '(//*[@class="safe-driving-setting__action edit-row"]//*[@class ="lytx lx-icon lx-edit"])[1]'
    invisible_delete_icon_only_root_group_xpath = '//*[@class="safe-driving-setting__action delete-row safe-driving-setting__invisible-action"]'

    # Config - Add-Ins
    delete_icon_xpath = '(//*[@class="safe-driving-setting__action delete-row"]//*[@class ="lytx lx-icon lx-trash"])[1]'
    addIns_delete_icon_xpath = '//div[contains(@class,"editable-list-item__body")][.//div[contains(@class,"editable-list-item__text") and contains(.,"EVSA")]] //*[@data-name="IconDelete2"]'
    create_add_in_xpath = '//*[@title="Add-In"]'
    config_text_area_xpath = '//textarea[@class="zen-textarea zen-text-input zen-form-field__input add-in-form__configurations"]'
    config_done_xpath = '//button[@title="Done"]'
    save_config_id = 'systemSettings_saveChangesButton'
    fbt_in_list_xpath = '//*[text()="fbtMyGeotab"]'
    eld_support_header_xpath = '//*[normalize-space()="ELD Support Config"]'
    eld_settings_validator_header_xpath = '//*[@class="intgr-page-header__page-name" and normalize-space()="ELD Settings Validator"]'
    evsa_header_xpath = '//*[@class="zen-page-header__page-name" and normalize-space()="Electric Vehicle Suitability Assessment"]'
    import_hos_logs_header_xpath = '//*[@class="intgr-page-header__page-name" and normalize-space()="Import HOS Logs"]'
    fbt_header_xpath = '//*[normalize-space()="Fringe Benefit Tax"]'
    hos_driver_summary_header_xpath = '//*[normalize-space()="HOS Driver Summary"]'
    map_show_addin_icon_xpath = '//*[@title="Show Add-Ins"]'
    compliance_data_summary_tab_in_map_xpath = '//*[text()="Compliance Data Summary"]'
    disabled_save_button_xpath = '//button[@id="systemSettings_saveChangesButton" and @disabled]'

    # Config > Holidays
    holidays_header_xpath = '//h1[@class="zen-page-header__page-name" and normalize-space()="Holidays"]'
    add_work_holiday_id = 'add-work-holiday'
    edited_holiday_name_xpath = '//tr[.//a[normalize-space()="testautobots-edited"]]//input[@type="checkbox"]'
    add_holiday_header_xpath = '//h1[@class="zen-page-header__page-name" and normalize-space()="Add Holiday"]'
    holiday_name_id = 'work-holiday-name-input'
    holiday_date_id = 'work-holiday-date-picker'
    holiday_group_id = 'work-holiday-group-input'
    cancel_holiday_xpath = '(//button[@id="cancel-work-holiday" and not(@disabled)])[1]'
    save_holiday_xpath = '(//button[@id="save-work-holiday" and not(@disabled)])[1]'
    default_group_id_xpath = '//*[@value="1"]'
    name_column_header_xpath = '//*[@data-column-id="name"]'
    date_column_header_xpath = '//*[@data-column-id="date"]'
    group_column_header_xpath = '//*[@data-column-id="groupid"]'

