class LocatorsFleetTelematicsLeftPanel:
    iframe_class = 'telematicsFrame'
    telematicsLoaded_xpath = '//*[@class="telematicsLoaded"]'
    more_charts_button = 'dashboard_MoreCharts'
    left_navigation_expand_mode_xpath = '//*[@class="left-navigation expanded"]'
    left_navigation_collapse_mode_xpath = '//*[@class="left-navigation collapsed"]'
    arrow_left_direction = '//button[@class="toggle-btn" and "lx-icon lx-arrow-forward rotate-180"]'
    arrow_right_direction = '//*[@class="lx-icon lx-arrow-forward"]'

    # Menu's in left navigation expand mode
    dashboard_menu_xpath = '//*[@class="menu-text" and text()=" Dashboard "]'
    map_menu_xpath = '//*[@class="menu-text" and text()=" Map "]'
    productivity_menu_xpath = '//*[@class="menu-text" and text()=" Productivity "]'
    compliance_menu_xpath = '//*[@class="menu-text" and text()=" Compliance "]'
    maintenance_menu_xpath = '//*[@class="menu-text" and text()=" Maintenance "]'
    sustainability_menu_xpath = '//*[@class="menu-text" and text()=" Sustainability "]'
    reports_menu_xpath = '//*[@class="menu-text" and text()=" Reports "]'
    rulesandexceptions_menu_xpath = '//*[@class="menu-text" and text()=" Rules & Exceptions "]'
    messages_menu_xpath = '//*[@class="menu-text" and text()=" Messages "]'
    notifications_menu_xpath = '//*[@class="menu-text" and text()=" Notifications "]'
    config_menu_xpath = '//*[@class="menu-text" and text()=" Config "]'

    # Productivity sub-menus and their sub-child links
    triphistory_submenu_xpath = '//*[@href="#/fleet-telematics/productivity/tripshistory"]'
    routes_submenu_xpath = '//*[@class="subitem-text"]//*[contains(text(), " Routes")]'
    plannedvsactualroutes_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/plannedvsactualroutes"]'
    routesummary_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/routesummary"]'
    unmatchedroute_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/unmatchedroute"]'
    importroutes_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/importroutes"]'
    publicworks_submenu_xpath = '//*[text()=" Public Works"]'
    routecompletion_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/routecompletion"]'
    materialmanagement_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/materialmanagement"]'
    zones_submenu_xpath = '//*[text()= " Zones" and //@class="subitem-text"]'
    zones_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/zones"]'
    zonetypes_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/zonetypes"]'
    zonevisits_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/zonevisits"]'
    importzones_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/importzones"]'
    drivercongregation_submenu_xpath = '//*[@href="#/fleet-telematics/productivity/drivercongregation"]'
    assetlocationsharing_submenu_xpath = '//*[@href="#/fleet-telematics/productivity/assetlocationsharing"]'
    riskmanagement_submenu_xpath = '//*[@href="#/fleet-telematics/productivity/riskmanagement"]'
    productivity_menu_dropdown_xpath = '//*[text()=" Productivity "]//following-sibling::*[@class="arrow"]'
    routes_submenu_dropdown_xpath = '//*[text()=" Routes"]//preceding::*[@class="lx-icon lx-sm-chevron-right"]'
    routes_subchild_xpath = '//*[@class="subchild-link" and text()=" Routes "]'
    publicworks_submenu_dropdown_xpath = '(//*[text()=" Public Works"]//preceding::*[@class="lx-icon lx-sm-chevron-right"])[last()]'
    zones_submenu_dropdown_xpath = '(//*[text()=" Zones"]//preceding::*[@class="lx-icon lx-sm-chevron-right"])[last()]'

    # Compliance sub-menus and their sub-child links
    compliance_menu_dropdown_xpath = '//*[text()=" Compliance "]//following-sibling::*[@class="arrow"]'
    hos_submenu_xpath = '//*[text()=" HOS"]'
    logs_xpath = '//*[@href="#/fleet-telematics/compliance/hoslogs"]'
    hos_submenu_dropdown_xpath = '//*[text()=" HOS"]//preceding::*[@class="lx-icon lx-sm-chevron-right"]'
    unidentified_driving_subchild_xpath = '//*[@href="#/fleet-telematics/compliance/unidentifieddriving"]'
    violations_subchild_xpath = '//*[@href="#/fleet-telematics/compliance/violations"]'
    availability_subchild_xpath = '//*[@href="#/fleet-telematics/compliance/availability"]'
    timecardreport_submenu_xpath= '//*[@href="#/fleet-telematics/compliance/timecardreport"]'
    iftareport_submenu_xpath = '//*[@href="#/fleet-telematics/compliance/iftareport"]'
    cleantruckcheck_submenu_xpath = '//*[@href="#/fleet-telematics/compliance/cleantruckcheck"]'

    # Maintenance sub-menus and their sub-child links
    maintenance_menu_dropdown_xpath = '//*[text()=" Maintenance "]//following-sibling::*[@class="arrow"]'
    assetinspection_submenu_xpath = '//*[@href= "#/fleet-telematics/maintenance/assetinspection"]'
    diagnostics_submenu_xpath = '//*[text()=" Diagnostics"]'
    reminders_submenu_xpath = '//*[@href= "#/fleet-telematics/maintenance/reminders"]'
    faults_subchild_xpath = '//*[@href = "#/fleet-telematics/maintenance/faults"]'
    measurements_subchild_xpath = '//*[@href = "#/fleet-telematics/maintenance/measurements"]'
    maintenance_center_sub_menu_xpath = '//span[@class="subitem-text"]/*[contains(text(), "Maintenance Center")]'
    speed_profile_subchild_xpath = '//*[@href="#/fleet-telematics/maintenance/speedprofile"]'
    Log_data_and_collisions_subchild_xpath = '//*[@href="#/fleet-telematics/maintenance/logdataandcollisions"]'
    work_order_sub_child_xpath = '//*[@href="#/fleet-telematics/maintenance/workorder"]'
    schedules_sub_child_xpath = '//*[@href="#/fleet-telematics/maintenance/schedules"]'


    # Sustainability sub-menus and their sub-child links
    sustainability_menu_dropdown_xpath = '//*[text()=" Sustainability "]//following-sibling::*[@class="arrow"]'
    sustainabilityoverview_submenu_xpath = '//*[@href= "#/fleet-telematics/sustainability/sustainabilityoverview"]'
    fuel_energy_usage_submenu_xpath = '//*[@href = "#/fleet-telematics/sustainability/fuelandevenergyusage"]'
    evbatteryhealth_submenu_xpath = '//*[@href="#/fleet-telematics/sustainability/evbatteryhealth"]'
    evcharginghistory_submenu_xpath = '//*[@href="#/fleet-telematics/sustainability/evcharging"]'
    bevrangecapability_submenu_xpath = '//*[@href="#/fleet-telematics/sustainability/bevrangecapability"]'

    # Reports sub-menus and their sub-child links
    reports_menu_dropdown_xpath = '//*[text()=" Reports "]//following-sibling::*[@class="arrow"]'
    myreports_submenu_xpath= '//*[@href= "#/fleet-telematics/insights/myreports"]'
    reportsetup_submenu_xpath = '//*[@href="#/fleet-telematics/insights/reportsetup"]'
    dashboard_subchild_xpath = '//*[@class = "subchild-link" and text() = " Dashboard "]'
    reportviews_subchild_xpath = '//*[@class = "subchild-link" and text() = " Report Views "]'
    emailedreports_subchild_xpath = '//*[@class = "subchild-link" and text() = " Emailed Reports "]'

    # Rules & Exceptions sub-menus and their sub-child links
    rules_submenu_xpath = '//*[@href="#/fleet-telematics/rules/rules" or @href="#/fleet-telematics/rulexception/rules"]'
    exceptions_submenu_xpath = '//*[@href="#/fleet-telematics/rules/exceptions" or @href="#/fleet-telematics/rulexception/exceptions"]'
    rulesandexceptions_menu_dropdown_xpath = '//*[text()=" Rules & Exceptions "]//following-sibling::*[@class="arrow"]'

    # Config sub-menus and their sub-child links
    fleet_settings_submenu_xpath = '//*[@href="#/fleet-telematics/config/settings"]'
    work_hours_submenu_xpath = '//*[@href="#/fleet-telematics/config/workhours"]'
    holidays_submenu_xpath = '//*[@href="#/fleet-telematics/config/holidays"]'
    audit_log_submenu_xpath = '//*[@href="#/fleet-telematics/config/auditlog"]'

    # Driver Safety
    fyinotify_submenu_xpath = '//*[@href="#/driver-safety/tasks/fyinotify"]'
    collisions_submenu_xpath = '//*[@href="#/driver-safety/tasks/collision"]'
    due_for_coaching_submenu_xpath = '//*[@href="#/driver-safety/tasks/coaching"]'
    assign_drivers_submenu_xpath = '//*[@href="#/driver-safety/tasks/assigndriver"]'
    insights_menu_xpath = '//*[text()=" Insights "]'
    open_tasks_report_submenu_xpath = '//*[@href="#/driver-safety/insights/opentasksreport"]'
    drivers_report_submenu_xpath = '//*[@href="#/driver-safety/insights/driversreport"]'
    group_report_submenu_xpath = '//*[@href="#/driver-safety/insights/groupreport"]'
    coaches_report_submenu_xpath = '//*[@href="#/driver-safety/insights/coachesreport"]'
    program_status_report_submenu_xpath = '//*[@href="#/driver-safety/insights/programstatusreport"]'
    behaviors_report_submenu_xpath = '//*[@href="#/driver-safety/insights/behaviorsreport"]'
    library_menu_xpath = '//*[text()=" Library "]'
    events_submenu_xpath = '//*[@href="#/driver-safety/library/events"]'
    coachinghistory_submenu_xpath = '//*[@href="#/driver-safety/library/coachinghistory"]'
    recognitionhistory_submenu_xpath = '//*[@href="#/driver-safety/library/recognitions"]'
    dataexport_submenu_xpath = '//*[@href="#/driver-safety/library/dataexport"]'
    search_submenu_xpath = '//*[text()=" Search "]'

    # Video Search
    vehicles_menu_xpath = '//*[@class="menu-text" and text()=" Vehicles "]'
    map_search_menu_xpath = '//*[@class="menu-text" and text()=" Map Search "]'
    vs_library_menu_xpath = '//*[@class="menu-text" and text()=" Library "]'
    saved_videos_submenu_xpath = '//*[@href = "#/lvs/library/saved"]'
    video_tags_submenu_xpath = '//*[@href = "#/lvs/library/tagged"]'

    # Admin
    users_menu_xpath = '//*[@class="menu-text" and normalize-space()="Users"]'
    admin_vehicles_menu_xpath = '//*[@class="menu-text" and normalize-space()="Vehicles"]'
    telematics_assets_menu_xpath = '//*[@class="menu-text" and normalize-space()="Telematics Assets"]'
    telematics_assets_menu_xpath_old_ui = '//*[text()="Telematics Assets"]'
    devices_menu_xpath = '//*[@class="menu-text" and normalize-space()="Devices"]'
    geofences_menu_xpath = '//*[@class="menu-text" and normalize-space()="Geofences"]'
    admin_insights_menu_xpath = '//*[@class="menu-text" and normalize-space()="Insights"]'
    insights_driver_id_menu_xpath = '//*[@href = "#/admin/insights/driverid"]'
    config_settings_menu_xpath = '//*[@class="menu-text" and normalize-space()="Config. Settings"]'

    # AddIns menu and its submenus
    addins_menu_xpath = '//span[contains(@class,"menu-text") and normalize-space()="Addins"]'
    fbt_submenu_xpath = '//*[@href="#/fleet-telematics/addins/FBT"]'
    hos_driver_summary_submenu_xpath = '//*[@href="#/fleet-telematics/addins/HOS%2520Driver%2520Summary"]'
    evsa_submenu_xpath = '//*[@href="#/fleet-telematics/addins/EV%2520Suitability%2520Assessment"]'
    import_hos_logs_submenu_xpath = '//*[@href="#/fleet-telematics/addins/Import%2520HOS%2520Logs"]'
    eld_info_config_submenu_xpath = '//*[@href="#/fleet-telematics/addins/ELD%2520Info%2520Config"]'
    eld_settings_validator_submenu_xpath = '//*[@href="#/fleet-telematics/addins/ELD%2520Settings%2520Validator"]'
    addins_menu_expand_xpath = '//*[@class="lx-icon lx-chevron-lrg-up"]'
    map_show_addin_icon_xpath = '//*[@title="Show Add-Ins"]'
    compliance_data_summary_tab_in_map_xpath = '//*[text()="Compliance Data Summary"]'