class LocatorsHos:

    hos_username_id = 'loggedInState_userText'
    hos_company_id = 'loggedInState_databaseNameId'
    hos_groups_filter_id = 'north'
    hos_iframe_class = 'eldFrame'
    walkme_iframe_id = 'helpGuide_iframe'
    compliance_menu = '//*[@class="menu-list-item__label"]//*[text()="Compliance"]'
    accept_cookies_button = '/html/body/div[1]/div[2]/div[2]/button[1]'
    compliance_hos_button = '//li[1]/button/div[2]/span[text()="HOS"]'
    compliance_hos_logs_button = '//span[text()="Logs"]'
    compliance_hos_violations_button = '//span[text()="Violations"]'
    drivers_drop_down = '//*[@id="selectDrivers"]/div/button'
    select_all = '//button/span[text()="Select all"]'
    apply_change_button = '/html/body/main/div/div[1]/div[2]/div[2]/div/div[3]/button'
    assets_menu_button = '(//span[text()="Assets"])[1]'
    assets_title = '/html/body/main/div[1]/div[1]/div/div[2]/div[1]/h1'
    hos_logs_title = '//h1[@class="geo-header__page-name ellipsis"]'
    hos_violations_title = '/html/body/main/div/div[1]/div[1]/div/div[2]/div[1]/h1[1]'
