class LocatorsEditUser:
    edit_user_title_xpath = './/*[@id="main-title"]'
    edit_group_button_xpath = '//*[@id="groupSelector"]/div'
    search_group_textbox_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                 'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/input'
    select_searched_group_button_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                         'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/' \
                                         'ngb-typeahead-window/button'
    done_button_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/multi-group-selector/' \
                        'div/div[3]/button[2]'
    select_role_xpath = '//*[@id="driveCamRoleSelector"]/div/span'
    role_dropdown_xpath = '//*[@id="driveCamRoleSelector"]/div/div/ul/li[4]'
    save_changes_button_xpath = '//*[@id="submit-button"]'
    first_id_textbox_xpath = '//*[@id="first-name-form"]/lytx-input/div/div[2]/input'
    delete_user_button_xpath = '//*[@id="delete-button"]/span'
    confirm_delete_user_xpath = '//*[@id="modalShellPrimaryButton"]'
    notification_tab_xpath = '//*[contains(text(),"Notifications")]'
    add_notification_button_xpath = '//*[text()=" Add Notification "]'
    notification_type_xpath = '//*[text()=" Select Notification Type "]'
    select_event_status_xpath = '//li/span[text()=" Event Status "]'
    select_status_button_xpath = '//input[@placeholder="Select Status"]'
    select_status_f2f_xpath = '//*[text()="Face-To-Face"]'
    dropdown_arrow_xpath = ('//*[contains(@placeholder, "Status Selected") or contains(@placeholder, "Select '
                            'Status")]/parent::div/parent::div/following-sibling::div')
    conditions_group_button_xpath = '//*[text()=" All Available Groups "]'
    conditions_search_group_textbox_xpath = '//input[@placeholder="Search Groups"]'
    conditions_select_group_dropdown_xpath = '//*[contains(text(), "Vehicle Needs Attention")]'
    conditions_done_button_xpath = '//*[text()="Done"]'
    reports_tab_xpath = '//*[contains(text(),"Reports")]'
    add_subscription_button_xpath = '//*[@id="add-report-button"]'
    select_report_xpath = '//*[text()=" Select Report "]'
    select_driving_summary_xpath = '//*[text()=" Driving Summary "]'
    select_insight_summary_report_xpath = '//*[text()=" Insights Summary Report "]'
    inactive_status_checkbox_xpath = '//*[@id="status-radio-button-inactive"]/label/div/i'
    active_status_checkbox_xpath = '//*[@id="status-radio-button-active"]/label/div/i'
    continue_status_button_xpath = '//*[@id="modalShellPrimaryButton"]'
    login_enabled_checkbox_xpath = '//*[@id="login-radio-buttons"]/lytx-radio-button[1]/label/div/i'
    login_disabled_checkbox_xpath = '//*[@id="login-radio-buttons"]/lytx-radio-button[2]/label/div/i'
    username_textbox_xpath = '//*[@id="username-form"]/lytx-input/div/div[2]/input'
    password_textbox_xpath = '//*[@id="password-form"]/lytx-input/div/div[2]/input'
    delete_notifications_xpath = '//button[contains(@class, "delete-icon")]'
    delete_reports_xpath = '//button[contains(@class, "delete-icon")]'
    updated_user_success_message_xpath = '//*[contains(text(), "successfully updated.")]'
    deleted_user_success_message_xpath = '//*[contains(text(), "successfully deleted.")]'
    first_row_driver_name_xpath = '(//cdk-row/cdk-cell[2]/span[2])[1]'
