class LocatorsAddUser:
    add_user_title_id = 'main-title'
    first_name_textbox_xpath = '//*[text()=" First Name "]/following-sibling::div/input'
    last_name_textbox_xpath = '//*[text()=" Last Name "]/following-sibling::div/input'
    employee_id_textbox_xpath = '//*[text()=" Employee ID "]/following-sibling::div/input'
    email_address_textbox_xpath = '//*[text()=" Email Address "]/following-sibling::div/input'
    cell_phone_textbox_xpath = '//*[@id="phoneNumberInput"]'
    login_enabled_checkbox_xpath = '//*[@id="login-radio-buttons"]/lytx-radio-button[1]/label/div/i'
    user_name_textbox_xpath = '//*[text()=" Username "]/following-sibling::div/input'
    password_textbox_xpath = '//*[text()=" Password "]/following-sibling::div/input'
    group_selector_xpath = '//*[@id="groupSelector"]/div'
    search_group_textbox_xpath = '//*[@placeholder="Search Groups"]'
    select_searched_group_button_xpath = '//*[@placeholder="Search Groups"]/parent::div//button'
    group_done_button_xpath = '//*[text()="Done"]'
    select_role_button_xpath = '//*[@id="driveCamRoleSelector"]/div/span'
    coach_role_button_xpath = '//*[@id="driveCamRoleSelector"]/div/div/ul/li/span[text()=" Coach "]'
    create_button_id = "submit-button"
    driver_role_button_xpath = '//*[text()=" Driver "]'
    lytx_badge_message_xpath = '//user-info/div/div[1]/div[5]/div[2]/div'
    cancel_button_xpath = '//*[text()=" Cancel "]'
    login_username_error_xpath = './/*[text()=" Username already exists. "]'
    cellphone_already_exists_error_xpath = './/*[text()=" Cell phone number already exists "]'
    Invalid_cell_phone_number = '//*[text()=" Invalid cell phone number "]'
    user_created_success_message_xpath = '//*[contains(text(), "been successfully created")]'
