class LocatorsGeotabPageAddInsPage:
    dashboard_xpath = '(//*[@href="#dashboard"])[1]'
    company_logo_xpath = '//*[@aria-label="Company logo"]'
    product_guide_header_xpath = '//*[text()="Product Guide"]'
    username_textbox_id = 'username'
    next_button_id = 'login-button'
    login_button_xpath = '//button[contains(normalize-space(), "Log")]'
    password_textbox_xpath  = '//*[@type="password"]'
    search_textbox_xpath = '(//input[@class="menu-search-field__input"])[1]'
    fbt_result_in_search_xpath = '(//*[@href="#addin-fbtmygeotab-fbtMyGeotab"])[2]'
    hos_driver_summary_result_in_search_xpath = '(//*[@href="#addin-hos_driver_summary-hosDriverSummary"])[2]'
    import_hos_logs_result_in_search_xpath = '(//*[@href="#addin-import_hos_logs-importHosLogs"])[2]'
    eld_support_result_in_search_xpath = '(//*[@href="#addin-eld_info-eldInfoAddinMygeotab"])[2]'
    eld_settings_validator_result_in_search_xpath = '(//*[@href="#addin-eldsettingsvalidator-eldSettingsValidator"])[2]'
    geo_dialog_yes_button_xpath = '//*[@class="geo-button" and text()="Yes"]'
    geo_dialog_header_xpath = '//*[text()="Long Running Report"]'
    map_menu_xpath = '(//*[@href="#map"])[1]'
    map_page_show_addin_icon_xpath = '//*[@aria-label="Show Add-Ins"]'
    compliance_data_summary_tab_xpath = '(//*[text()="Compliance Data Summary"])[1]'
    evsa_result_in_search_xpath = '(//*[@href="#addin-evsa-index"])[2]'
    evsa_page_header_xpath = '//*[@class="zen-page-header__page-name" and text()="Electric Vehicle Suitability Assessment"]'
    eld_support_page_header_xpath = '//*[@class="intgr-page-header__page-name" and //*[text()="ELD Support Config"]]'
    import_hos_logs_page_header_xpath = '//*[@class="intgr-page-header__page-name" and //*[text()="Import HOS Logs"]]'
    eld_settings_validator_page_header_xpath = '(//*[@class="intgr-page-header__page-name" and //*[text()="ELD Settings Validator"]])[1]'
    fbt_page_header_xpath = '//*[text()=" Fringe Benefit Tax "]'
    hos_driver_summary_page_header_xpath = '//*[@class="intgr-page-header__page-name" and //*[text()="HOS Driver Summary"]]'



