class LocatorsLocationPage:
    div_page_title='(//div[@class="title-heading"]//child::*)[1]'
    location_menu_icon = '//div[@mattooltip="Locations"]'
    highlighted_location_menu_icon = '//div[@class="tab-parent tab-parent-bgc"]//div[@mattooltip="Locations"]//div[@class="icon-label"]'
    add_location_btn = '//button[@color="primary"]'
    cross_icon_pop_up = '//mat-dialog-container//span[@class="close-icon"]'
    add_location_pop_title = '//div[@class="container"]//p[@class="addtitle"]'
    location_name = '//input[@name="siteName"]//parent::div/label'
    location_txt_box ='//input[@name="siteName"]'
    location_mandatory_sign = '//input[@name="siteName"]//parent::div/label/span[@class="required"]'
    email_name = '//input[@name="email"]//parent::div/label'
    email_txt_box = '//input[@name="email"]'
    email_mandatory_sign = '//input[@name="email"]//parent::div/label/span[@class="required"]'
    first_name = '//input[@name="firstName"]//parent::div/label'
    first_name_txt_box = '//input[@name="firstName"]'
    first_name_mandatory_sign = '//input[@name="firstName"]//parent::div/label/span[@class="required"]'
    last_name = '//input[@name="lastName"]//parent::div/label'
    last_txt_box = '//input[@name="lastName"]'
    last_name_mandatory_sign = '//input[@name="lastName"]//parent::div/label/span[@class="required"]'
    phone_no = '//input[@name="phone"]//parent::div/label'
    phone_no_txt_box = '//input[@name="phone"]'
    phone_no_mandatory_sign = '//input[@name="phone"]//parent::div/label/span[@class="required"]'
    country = '//select[@name="country"]//parent::div/label'
    country_dropdown = '//select[@name="country"]'
    country_mandatory_sign = '//select[@name="country"]//parent::div/label/span[@class="required"]'
    country_ph = '(//select[@name="country"]//option)[1]'
    all_country = '//select[@name="country"]//option'
    usa_country = '//select[@name="country"]//option[@value="UNITED STATES"]'
    canada_country = '//select[@name="country"]//option[@value="CANADA"]'
    address = '//input[@name="address1"]//parent::div/label'
    address_txt_box = '//input[@name="address1"]'
    address_mandatory_sign = '//input[@name="address1"]//parent::div/label/span[@class="required"]'
    address_2 = '//input[@name="address2"]//parent::div/label'
    address_2_txt_box = '//input[@name="address2"]'
    city = '//input[@name="city"]//parent::div/label'
    city_txt_box = '//input[@name="city"]'
    city_mandatory_sign = '//input[@name="city"]//parent::div/label/span[@class="required"]'
    state = '//input[@name="state"]//parent::div/label'
    state_txt_box = '//input[@name="state"]'
    state_dropdown = '//select[@name="state"]'
    state_mandatory_sign = '//input[@name="state"]//parent::div/label/span[@class="required"]'
    postal_code = '//input[@name="postalCode"]//parent::div/label'
    postal_code_txt_box = '//input[@name="postalCode"]'
    postal_code_mandatory_sign = '//input[@name="postalCode"]//parent::div/label/span[@class="required"]'
    cancel_btn = '//button[@class="lytx__btn lytx__btn__cancle"]'
    inactive_save_btn = '//button[@type="submit" and contains(@class,"disabled")]'
    active_save_btn = '//button[@type="submit" and contains(@class,"lytx__btn_active")]'
    inactive_toggle_off = '//button[@aria-pressed="false" ]//span[contains(text(),"Inactive")]'
    active_toggle_on = '//button[@aria-pressed="true" ]//span[contains(text(),"Active")]'
    inactive_toggle_on = '//button[@aria-pressed="true" ]//span[contains(text(),"Inactive")]'
    active_toggle_off = '//button[@aria-pressed="false" ]//span[contains(text(),"Active")]'
    yes_btn_popup = '//app-confirmation-modal//button[@class="close-button"]'
    success_notifi_txt = '//mat-snack-bar-container//span'
    success_notifi_icon = '//mat-icon[contains(@class,"check-icon")]'
    success_notifi_cross_icon = '(//mat-snack-bar-container//mat-icon)[2]'
    recent_location_name = '//td[@id="location_locationname_0"]'
    recent_location_address = '//td[@id="location_locationaddress_0"]'
    recent_contact_name = '//td[@id="location_locationscontact_0"]//a'
    recent_contact_no = '//td[@id="location_locationscontact_0"]//span[@class="contact_name"]'
    recent_active_toggle = '//td[@id="location_active_0"]//input'
    first_location_edit_btn = '//td[@id="location_edit_0"]//span'
    welcome_popup = '// *[text() = "Welcome"]'
    welcome_popup_logo = '//div[contains(@class,"lytxLogo")]'
    welcome_popup_title = '//div[@class="parent-modal"]//span[@class="headingText"]'
    welcome_popup_content = '//div[@class="info-container"]'
    welcome_last_popup_content = '//span[@class="middle-context"]'
    welcome_last_popup_content_bold = '//div[@class="main-context"]//strong'
    welcome_popup_close_btn = '//mat-dialog-container//span[@class="close-icon1"]'
    welcome_primary_btn = '//div[@class="footer"]//button[contains(@class,"primary")]//span[contains(@class,"label")]'
    welcome_secondary_btn = '//div[@class="footer"]//button[contains(@class,"first-btn")]//span[contains(@class,"label")]'
    welcome_page_steps_info = '//div[@class="main-context"]//p'
    welcome_page_step1 = '(//div[@class="main-context"]//ol//li)[1]'
    welcome_page_step2 = '(//div[@class="main-context"]//ol//li)[2]'
    welcome_page_step3 = '(//div[@class="main-context"]//ol//li)[3]'
    welcome_page_stepheading1 = '(//div[@class="main-context"]//ul//li//strong)[1]'
    welcome_page_stepheading2 = '(//div[@class="main-context"]//ul//li//strong)[2]'
    welcome_page_stepheading3 = '(//div[@class="main-context"]//ul//li//strong)[3]'
    welcome_page_step_content1 = '(//div[@class="main-context"]//ul//li//span)[1]'
    welcome_page_step_content2 = '(//div[@class="main-context"]//ul//li//span)[2]'
    welcome_page_step_content3 = '(//div[@class="main-context"]//ul//li//span)[3]'
    support_center = '//label[@class="question"]'
    support_center_logo_txt = '//a[contains(@class,"logo-link")]//span'
    supp_center_loader = '//lightning-spinner'
    search_txt_box = "//input[@placeholder='Search']"
    table_result = '//tbody//tr'
    import_location_btn = '//span[contains(@class,"import_button")]'
    download_location_list = "//span[contains(@class,'csv')]"
    pgn_next_btn = '//ul[@class="pagination"]//a[@aria-label="Next"]'
    pgn_previous_btn = '//ul[@class="pagination"]//a[@aria-label="Previous"]'
    status_filter = '//select[@id="filter_by_site"]'
    active_option = '//select[@id="filter_by_site"]//option[@value="true"]'
    table_result_checkbox = '//tr//input[@type="checkbox"]'
    inactive_option = '//select[@id="filter_by_site"]//option[@value="false"]'
    show_rows_dropdown = '//select[@class="row-select"]'
    rows_100_option = '//select[@class="row-select"]//option[@value="100"]'
    rows_150_option = '//select[@class="row-select"]//option[@value="150"]'
    rows_200_option = '//select[@class="row-select"]//option[@value="200"]'
    rows_250_option = '//select[@class="row-select"]//option[@value="250"]'