class LocatorsConfigurationSetting:
    tier1_full_access_role_text_xpath = '//*[text()="Full Access"]'
    tier1_label_xpath = '//*[@id="rolePermissionInfo"]/div/div[1]/div[1]'
    add_new_tier_button_xpath = '//*[text()=" Add New Tier "]'
    select_roles_button_xpath = '//*[@placeholder="Select Roles"]'
    select_first_role_dropdown_xpath = '/html/body/ngb-modal-window/div/div/role-tier-modal/lytx-modal-shell/' \
                                       'div/div[2]/div[2]/div[2]/multiselect-typeahead/div/div[1]/div/' \
                                       'multiselect-typeahead-window/button[1]/i'
    confirm_select_roles_button_xpath = '//*[@id="modalShellPrimaryButton"]'
    new_role_tier2_text_xpath = '//*[text()="API Developer"]'
    edit_tier_button_xpath = '//*[@id="editIcon"]'
    edit_role_button_xpath = '//*[@id="roleFilter"]/div/div[1]'
    select_edit_role_option_xpath = '//*[@class="multiselect-dropdown-item"]//*[text()="API Developer Read Only"]'
    confirm_edit_role_button_xpath = '/html/body/ngb-modal-window/div/div/role-tier-modal/lytx-modal-shell/div/' \
                                     'div[2]/div[3]/button[2]'
    delete_tier_button_id = 'deleteIcon'
    confirm_delete_tier_button_xpath = '/html/body/ngb-modal-window/div/div/action-modal/lytx-modal-shell/' \
                                       'div/div[2]/div[3]/button[2]'
    select_role_double_click_xpath = '/html/body/ngb-modal-window/div/div/role-tier-modal/lytx-modal-shell/' \
                                     'div/div[2]/div[1]'
    second_edited_role_xpath = '//*[text()="API Developer Read Only"]'
    unranked_tier_text_xpath = '//*[text()=" Unranked Tier "]'
    already_selected_role = '//*[@class="multiselect-dropdown-item selected"]//*[text()="API Developer Read Only"]'
    config_settings_page_title_xpath = '//*[text()="Configuration Settings"]'
    coaching_workflow_tab_xpath = '//*[text()="Coaching Workflows"]'
    workflows_title = '//*[@class="title"]'
    create_workflow_button = '//*[@class="lx-btn-primary lx-btn-small height"]'
    groups_button = '//*[@class="lx-btn lx-btn-text icon-group action--4"]'
    duplicate_button = '//*[@class="lx-icon lx-coaching-history"]'
    edit_button = '//*[@class="lx-icon lx-edit"]'
    delete_button = '//*[@class="lx-icon lx-trash"]'
    download_button = '//*[contains(@class,"lx-icon lx-download")]'
    create_workflow_title = '//*[text()="Create Workflow"]'
    group_filter_xpath = '//*[text()=" Filter By Group "]'
    search_group_textbox_xpath = '//input[@placeholder="Search by Group"]'
    select_searched_group_xpath = '//*[text()="Vehicle Needs Attention"]'
    search_group_done_button_xpath = '//*[text()="Done"]'
    first_group_name = '//*[text()="Vehicle Needs Attention"]'
    edit_workflow_title = '//*[text()="Edit Workflow"]'
    workflow_name_field_xpath = '//*[@class="lx-input-field ng-untouched ng-pristine ng-invalid"]'
    workflow_existing_name_field_xpath = '(//*[@class="lx-input-field ng-untouched ng-pristine ng-valid"])[1]'
    workflow_new_name_field_xpath = '//*[@class="lx-input-field ng-pristine ng-valid ng-touched"]'
    behaviour_dropdown_xpath = '//*[@class="dropdown__input-container"]/div'  # //*[@class="dropdown__input-container"]
    behaviour_from_dropdown_xpath = '//*[text()="Aggressive"]'
    coaching_status_dropdown_xpath = '(//*[@class="dropdown__select__content"])[3]'
    coaching_status_from_dropdown_xpath = '(//*[text()=" Collision "])[2]'
    custom_score_field_xpath = '//*[text()=" Event Score Override "]/parent::div//input'
    save_button = 'fullScreenModalShellPrimaryButton'
    search_filed_in_workflow_page = 'searchInput'
    first_workflow_name_xpath = '//*[@class="name-container"]/span'
    delete_existing_behaviour_xpath = '//*[@class="lx-icon lx-trash delete-behavior-button"]'
    update_popup_message_xpath = '//*[@aria-label="Successfully updated the workflow"]'
    delete_existing_rule_xpath = '(//*[@class="lx-icon lx-trash delete-behavior-button"])[1]'
    behaviour_dropdown_duplicate_xpath = '(//*[@data-test-id="dropdown-input"])[1]'
    behaviour_from_dropdown_duplicate_xpath = '//*[text()="Backing"]'
    coaching_status_dropdown_duplicate_xpath = '(//*[@class="dropdown__select__content"])[3]'
    coaching_status_from_dropdown_duplicate_xpath = '(//*[text()=" Camera Issue "])[2]'
    custom_score_field_duplicate_xpath = '(//input[@class="lx-input-field ng-untouched ng-pristine ng-valid"])[2]'
    delete_in_popup_xpath = '//*[text()=" Delete "]'
    delete_popup_message_xpath = '//*[@aria-label="Workflow deleted successfully."]'
    add_behavior_button_xpath = '//*[text()=" Add Behavior "]'
    reset_button_xpath = '//*[@class="lx-icon lx-reset"]'
    close_button = 'fullScreenModalShellSecondaryButton'
    role_label_xpath = '//*[contains(text(), " Role")]'
    description_label_xpath = '(//*[contains(text(), " Description ")])[1]'
    admin_permission_label_xpath = '(//*[contains(text(), "Admin Permission ")])[1]'
    first_tier_edit_icon_id = 'editIcon'
    edit_icon_for_second_tier_xpath = '(//*[@id="editIcon"])[2]'
    delete_icon_for_second_tier_id = 'deleteIcon'
    workflow_count_xpath = '//*[@class="filter-header-bar__title__count--value"]'
    program_configuration_tab_xpath = '//*[text()="Program Configuration"]'
    critical_distance_text_xpath = '//feature//*[text()=" Critical Distance "]'
    audio_alerts_text_xpath = '(//sub-feature//*[text()=" Audio Alerts "])[1]'
    led_alerts_text_xpath = '(//sub-feature//*[text()=" LED Alerts "])[1]'
    events_text_xpath = '(//sub-feature//*[text()=" Events "])[1]'
    following_distance_text_xpath = '//feature//*[text()=" Following Distance "]'
    audio_alerts_for_following_distance_text_xpath = '(//sub-feature//*[text()=" Audio Alerts "])[2]'
    led_alerts_for_following_distance_text_xpath = '(//sub-feature//*[text()=" LED Alerts "])[2]'
    events_for_following_distance_text_xpath = '(//sub-feature//*[text()=" Events "])[2]'
    lane_departure_text_xpath = '//feature//*[text()=" Lane Departure "]'
    audio_alerts_for_lane_departure_text_xpath = '(//sub-feature//*[text()=" Audio Alerts "])[3]'
    led_alerts_for_lane_departure_text_xpath = '(//sub-feature//*[text()=" LED Alerts "])[3]'
    events_for_lane_departure_text_xpath = '(//sub-feature//*[text()=" Events "])[3]'
    rolling_stop_text_xpath = '//feature//*[text()=" Rolling Stop "]'
    audio_alerts_for_rolling_stop_text_xpath = '(//sub-feature//*[text()=" Audio Alerts "])[4]'
    led_alerts_for_rolling_stop_text_xpath = '(//sub-feature//*[text()=" LED Alerts "])[4]'
    events_for_rolling_stop_text_xpath = '(//sub-feature//*[text()=" Events "])[4]'
    action_plan_tab_xpath = '//*[@class="tab-text" and text()="Action Plan"]'
    name_text_xpath = '//*[text()=" Name "]'
    description_text_xpath = '//*[text()=" Description "]'
    edit_button_id = 'editIcon'
    delete_button_id = 'deleteIcon'
    edit_button_in_action_plan_xpath = '//*[@class="corrective-actions-table__edit-btn"]'
    delete_button_in_action_plan_xpath = '(//*[@aria-label="Delete"])[2]'
    confirm_delete_corrective_action_button_xpath = '//*[text()=" Delete "]'
    corrective_action_title_text_xpath = '//*[@class="corrective-actions-table__title"]'
    add_corrective_action_xpath = '//*[text()=" Add Corrective Action "]'
    add_corrective_action_button_xpath = '//*[@class="add-action-btn"]'
    corrective_action_name_textbox_xpath = '//*[@class="action-level-name ng-untouched ng-pristine ng-invalid"]'
    corrective_action_description_textbox_xpath = '//*[@class="action-level-description ng-untouched ng-pristine ng-invalid"]'
    added_corrective_action_text_xpath = '//div[normalize-space(text())="Test name"]'
    save_corrective_action_button_xpath = '//*[@class="footer-save-btn btn btn-primary"]'
    close_icon_button_xpath = '/html/body/ngb-modal-window/div/div/add-or-edit-workflow/lytx-full-screen-modal-shell/div/div[1]/div[1]/i'
    modify_groups_button_in_groups_popup_xpath = '//*[@id="fullScreenModalShellPrimaryButton"]'
    select_group_in_groups_popup_xpath = '(//*[contains(@class,"lx-icon group-checkbox")])[5]'
    done_button_xpath = '(//*[contains(@class,"multi-group-selector-bottom-done")])'
    save_button_xpath = '//*[@id="modalShellPrimaryButton"]'
    close_button_xpath = '//*[@id="fullScreenModalShellSecondaryButton"]'
    search_by_group_field_xpath = '//*[@data-test-id="typeahead-search-input"]'
    select_group_xpath = '(//*[contains(@class, "dropdown-item")])[1]'
    group_done_button_xpath = '//*[text()="Done"]'
    role_hierarchy_tab_xpath = '//*[@class="tab-text" and text()="Role Hierarchy"]'
    duplicate_workflow_name_error_message_xpath = '//*[@aria-label="Duplicate workflow name. Please enter a unique name."]'
    discard_changes_popup_xpath = '//*[text()=" Discard "]'
    description_xpath = '//*[contains(text(), "Manage your company’s event handling rules, enabled behaviors")]'
    note_xpath = '//*[contains(text(), " Some fields are locked and can’t be edited directly")]'
    existing_behavior_close_button_xpath = '//ngb-modal-window//dropdown-typeahead//i[contains(@class,"close") or contains(@class,"clear")]'
    existing_coaching_status_close_button_xpath = '//ngb-modal-window//dropdown//i[contains(@class,"close") or contains(@class,"clear")]'

    # In-Cab MVAI Locators
    incab_mvai_tab_xpath = '//div[@data-test-id="lx-tab-1" and contains(normalize-space(.), "In-Cab MV+AI")]'
    incab_mvai_page_title_xpath = '//div[@id="category-title"]//span[normalize-space()="In-Cab MV+AI"]'
    incab_mvai_description_xpath = '//div[@class="category__description" and contains(normalize-space(.), "These features are compatible with SF300 devices and newer")]'
    smoking_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Smoking"]'
    food_drink_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Food and Drink"]'
    inattentiveness_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Inattentiveness"]'
    lens_obstruction_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Lens Obstruction"]'
    handheld_device_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Handheld Device"]'
    no_seatbelt_feature_header_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="No Seatbelt"]'
    incab_mvai_save_button_xpath = '//span[contains(@class,"save-button-text") and normalize-space()="Save Changes"]'
    smoking_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Smoking"]/following::span[contains(@class,"lx-checkbox")][1]'
    smoking_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Smoking"]/following::span[contains(@class,"lx-checkbox")][2]'
    smoking_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Smoking"]/following::span[contains(@class,"lx-checkbox")][3]'
    food_drink_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Food and Drink"]/following::span[contains(@class,"lx-checkbox")][1]'
    food_drink_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Food and Drink"]/following::span[contains(@class,"lx-checkbox")][2]'
    food_drink_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Food and Drink"]/following::span[contains(@class,"lx-checkbox")][3]'
    inattentiveness_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Inattentiveness"]/following::span[contains(@class,"lx-checkbox")][1]'
    inattentiveness_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Inattentiveness"]/following::span[contains(@class,"lx-checkbox")][2]'
    inattentiveness_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Inattentiveness"]/following::span[contains(@class,"lx-checkbox")][3]'
    lens_obstruction_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Lens Obstruction"]/following::span[contains(@class,"lx-checkbox")][1]'
    lens_obstruction_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Lens Obstruction"]/following::span[contains(@class,"lx-checkbox")][2]'
    lens_obstruction_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Lens Obstruction"]/following::span[contains(@class,"lx-checkbox")][3]'
    handheld_device_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Handheld Device"]/following::span[contains(@class,"lx-checkbox")][1]'
    handheld_device_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Handheld Device"]/following::span[contains(@class,"lx-checkbox")][2]'
    handheld_device_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="Handheld Device"]/following::span[contains(@class,"lx-checkbox")][3]'
    no_seatbelt_audio_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="No Seatbelt"]/following::span[contains(@class,"lx-checkbox")][1]'
    no_seatbelt_led_alerts_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="No Seatbelt"]/following::span[contains(@class,"lx-checkbox")][2]'
    no_seatbelt_events_checkbox_xpath = '//span[contains(@class,"feature__header__name") and normalize-space()="No Seatbelt"]/following::span[contains(@class,"lx-checkbox")][3]'
    smoking_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of driver smoking while the vehicle is in motion."]'
    food_drink_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of driver eating or drinking while the vehicle is in motion."]'
    inattentiveness_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of lacking sufficient focus on the road while the vehicle is in motion."]'
    lens_obstruction_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of obstruction of the inside lens while the vehicle is in motion."]'
    handheld_device_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of driver holding and/or actively using a handheld device while the vehicle is in motion."]'
    no_seatbelt_description_xpath = '//div[contains(@class,"feature__description") and normalize-space()="Detection of driver not wearing or improperly wearing the seatbelt while the vehicle is in motion."]'
    confirmation_popup_save_button_id = 'modalShellPrimaryButton'
    alert_success_message_xpath = '//div[@role="alertdialog" and @aria-label="Changes saved successfully"]'





