class LocatorsUserManagement:
    # user management table columns
    user_management_label_xpath = '//*[text()="User Management"]'
    users_tab_xpath = '//*[contains(text(),"Users")]'
    user_count_xpath = './/*[@class="filter-header-bar__title__count--value--success"]'
    name_label_xpath = '//*[@id="sortableContainerUserName"]/span[1]'
    employee_id_label_xpath = '(//*[text()=" Employee Id "])[1]'
    lytx_badge_label_xpath = '(//*[text()=" Lytx Badge "])[1]'
    primary_driver_group_label_xpath = '//cdk-header-cell//*[text()=" Primary Driver Group "]'
    roles_label_xpath = '//cdk-header-cell//span[text()=" Roles (Group) "]'
    status_label_xpath = '//cdk-header-cell//span[text()=" Status "]'
    login_label_xpath = '//cdk-header-cell//span[text()=" Login "]'
    username_label_xpath = '//cdk-header-cell//span[text()=" Username "]'
    total_page_count_xpath = '//download-csv'

    # Filters
    group_filter_first_button_xpath = '//*[text()=" Select Group(s) "]'
    search_group_filter_textbox_xpath = '//*[@placeholder="Search Groups"]'
    select_searched_group_filter_xpath = '//*[@class="dropdown-item__bottom"]'
    done_group_filter_button_xpath = '//button/*[text()="Done"]'
    roles_filter_button_xpath = '//*[@id="roleFilter"]/div/div[1]/div/input'
    select_roles_filter_xpath = '//*[@id="multiselect-typeahead-0-3"]/i'
    apply_select_role_xpath = '//*[text()="User Management"]'
    login_filter_button_xpath = '//*[@id="loginFilter"]/div/span/span'
    select_login_filter_xpath = '//*[@id="loginFilter"]/div/div/ul/li[1]'
    status_filter_button_xpath = '//*[@id="statusFilter"]/div/span'
    select_status_filter_xpath = '//*[@id="statusFilter"]/div/div/ul/li[2]'
    search_filter_textbox_xpath = '//*[@id="searchInput"]'
    reset_button_xpath = '//*[text()="Reset"]'
    clear_search_button_xpath = '//*[@id="clearSearchButton"]'
    close_status_filter = '//*[@id="statusFilter"]//*[@class="lx-icon lx-close-x"]'
    select_all_checkbox_xpath = '//cdk-header-row/cdk-header-cell[1]/i'
    roles_filter_active_xpath = '//*[@id="statusFilter"]/div/div/ul/li[1]'
    add_user_button_xpath = '//*[text()=" Add user "]'
    user_added_text_xpath = '/html/body/app-root/shell/div/div/div/user-list/div/div[2]/lx-table/div[2]/' \
                            'div[2]/cdk-table/cdk-row[3]/cdk-cell[2]/span[2]/span'
    first_row_user_text_xpath = '//cdk-table/cdk-row[1]/cdk-cell[2]/span[2]/span'
    roles_first_row_text_xpath = '//cdk-table/cdk-row[1]/cdk-cell[6]/span[2]/span'
    status_first_user_xpath = '(//cdk-cell[contains(@class, "cdk-column-Status")]//span[contains(@class, "cell-value")]//span)[1]'
    driver_id_of_first_user_xpath = '//cdk-table/cdk-row[1]/cdk-cell[4]/span[2]/div/span'

    user_edited_text_xpath = '/html/body/app-root/shell/div/div/div/user-list/div/div[2]/lx-table/div[2]/' \
                             'div[2]/cdk-table/cdk-row[4]/cdk-cell[2]/span[2]/span'
    login_first_user_text_xpath = '//cdk-table/cdk-row[1]/cdk-cell[8]/span[2]/span'
    second_user_text_xpath = '//cdk-table/cdk-row[2]/cdk-cell[2]/span[2]/span'
    second_user_status_xpath = '//cdk-row[2]/cdk-cell[7]/span[2]/span'
    filtered_user_login_xpath = '//cdk-table/cdk-row[1]/cdk-cell[8]/span[2]/span'
    select_active_status_xpath = '//*[@id="statusFilter"]//li//span[text()=" Active "]'
    check_first_user_xpath = '//cdk-table/cdk-row[1]/cdk-cell[1]/div/div/i'
    batch_delete_user_button_xpath = '//button[text()="Delete Users"]'
    confirm_button_batch_delete_user_xpath = '//*[text()=" Confirm "]'
    clear_status_filter_xpath = '//*[@id="statusFilter"]//i'
    status_of_deleted_user_xpath = '/html/body/app-root/shell/div/div/div/user-list/div/div[2]/lx-table/div[2]' \
                                   '/div[2]/cdk-table/cdk-row[1]/cdk-cell[7]/span[2]/span'
    edit_group_button_xpath = '//*[text()="Edit Group"]'
    group_filter_on_edit_group_dialog_xpath = '/html/body/ngb-modal-window/div/div/bulk-move-group/bulk-action-modal' \
                                              '/lytx-modal-shell/div/div[2]/div[2]/div/lx-tabs/div[2]/form/group-change' \
                                              '/div/div[3]/group-role-selector/div[1]/div[1]/multi-group-filter/div'
    search_group_textbox_on_edit_group_dialog_xpath = '/html/body/ngb-modal-window[2]/div/div/multi-group-selector-modal' \
                                                      '/multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/input'
    select_searched_group_on_edit_group_dialog_xpath = '/html/body/ngb-modal-window[2]/div/div/multi-group-selector-modal' \
                                                       '/multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/' \
                                                       'ngb-typeahead-window/button'
    done_button_on_edit_group_dialog_xpath = '//*[text()="Done"]'
    role_filter_on_edit_group_dialog_xpath = '(//*[text()=" Select Role "])[1]'
    select_driver_role_on_edit_group_dialog_xpath = '//*[text()=" Driver "]'
    apply_button_on_edit_group_dialog_xpath = '//*[text()=" Apply "]'
    delete_status_xpath = '//*[text()=" Deleted "]'
    change_status_button_xpath = '//*[text()="Change Status"]'
    inactive_status_radio_button_xpath = '//user-status//*[text()=" Inactive "]'
    apply_button_on_set_user_status_xpath = '//*[text()=" Apply "]'
    more_action_xpath = '//*[text()=" More Options "]'
    edit_login_button_xpath = '//*[text()="Edit Login"]'
    apply_button_on_edit_login_xpath = '//*[text()=" Apply "]'
    restore_user_button_xpath = '//*[text()="Restore user"]'
    edit_user_link = './/*[@class="lx-link edit-user-link"]'
    driver_id_tab_xpath = '/html/body/app-root/shell/div/div/navigation/div[1]/div[2]'
    devices_tab_xpath = './/*[@class="lx-icon lx-lftnav-devices"]'
    vehicles_tab_xpath = '//*[contains(text(), "Vehicles")]'
    equipment_management_tab_xpath = '//*[contains(text(), "Equipment")]'

    insights_tab_xpath = '//*[contains(text(),"Insights")]'
    driver_id_assignment_tab_xpath = '(//*[translate(normalize-space(), "driveridassignment", "DRIVERIDASSIGNMENT")="DRIVER ID ASSIGNMENT" ])[position() = 1 or position() = 2]'
    device_health_tab_xpath = '//div[text()=" DEVICE HEALTH "]'
    config_setting_tab_xpath = '//*[contains(text(), "Config. Settings")]'
    geofences_tab_xpath = '(//*[contains(text(), "Geofences")])[1]'

    # driver badge model
    cancel_button_xpath = '//*[@id="cancelButton"]'
    download_badge_button_xpath = '/html/body/ngb-modal-window/div/div/preview-badge/div/div[4]/button[2]'
    email_badge_button_xpath = '/html/body/ngb-modal-window/div/div/preview-badge/div/div[4]/button[3]'

    users_deleted_success_message_xpath = '//*[contains(text(), "users deleted.")]'
    status_updated_success_message_xpath = '//*[contains(text(), "users updated.")]'
    qr_code_xpath = '//*[@id="qr-code"]'
    user_moved_success_message_xpath = '//*[contains(text(), "user moved.")]'
    paginator_xpath = '//*[contains(@class, "paginator ")]'
    download_csv_xpath = '//*[(@class="download-csv")]'

    # user consent
    first_user_xpath = '(//*[@class="checkbox"])[1]'
    more_options_xpath = '//*[@class="more-options kebab-options"]'
    request_user_consent_xpath = '//*[text()="Request User Consent"]'
    request_user_consent_title_xpath = '//*[text()="Request User Consent"]'
    facial_id_checkbox_xpath = '(//*[@class="lx-icon table-checkbox lx-checkbox-inactive"])[1]'
    communication_mode_email_xpath = '(//*[@class="lx-icon table-checkbox lx-checkbox-inactive"])[1]'
    next_button_xpath = '//*[text()=" Next "]'
    send_request_button_xpath = '//*[text()=" Send Request "]'
    confirm_request_title_xpath = '//*[text()="Confirm Request"]'
    success_message_xpath = '//*[@aria-label="User consent request sent successfully!"]'

    # View change history
    change_view_history_xpath = '//*[@ngbtooltip="View Change History"]'
    user_affected_label_xpath = '//cdk-header-cell//span[text()="User Affected"]'
    action_label_xpath = '//cdk-header-cell//span[text()="Action"]'
    action_details_label_xpath = '//cdk-header-cell//span[text()=" Action Details "]'
    editor_label_xpath = '//cdk-header-cell//span[text()="Editor"]'
    action_date_label_xpath = '//cdk-header-cell//span[text()="Action Date"]'
    user_audit_log_tab_header_xpath = '//*[contains(text(), "User Audit Log")]'
    search_user_affected_textbox_xpath = '//*[@placeholder="Search User Affected"]'
    no_audit_logs_message_xpath = '//*[contains(@class,"lx-table__table__empty-message")]'
    first_user_affected_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[1]'
    reset_button_audit_page_xpath = '//*[@class="audit-log-modal-shell"]//*[text()="Reset"]'
    action_type_dropdown_xpath = '//*[text()=" Select Action(s) "]'
    select_action_type_xpath = '//li/span[text()=" Added "]'
    select_imported_xpath = '//li/span[text()=" Imported "]'
    action_type_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[2]'
    action_type_added_text_xpath = '(//span[contains(@class,"cell-value")]//span[normalize-space()="Added"])[1]'
    date_range_dropdown_xpath = '//*[@data-test-id="dateRange-filter-dropdown"]'
    select_date_range_today_xpath = '//span[contains(@class, "today")]'
    apply_button_xpath = '//*[text()="Apply"]'
    action_date_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[5]'
    close_user_audit_log_xpath = '//*[contains(text(), "Close")]'
    user_audit_log_tab_xpath = '//*[@modalcomponentname="UserAuditLog"]'
    download_log_button_xpath = '//span[text()="Download Log"]'
    download_log_button_disabled_xpath = '//*[@class="audit-download"]//button[@disabled]'
    group_row_text_xpath = '//cdk-table/cdk-row[{row}]/cdk-cell[6]/span[2]/span'
    employee_id_textbox_xpath = '//*[text()=" Employee ID "]/following-sibling::div/input'
    previous_page_disabled_xpath = '//span[contains(@class,"paging__pages--left-disabled")]'
    next_page_disabled_xpath = '//span[contains(@class,"paging__pages--right-disabled")]'
    previous_page_enabled_xpath = '//span[contains(@class,"paging__pages--left")]//i[contains(@class,"lx-chevron-lrg-left")]'
    next_page_enabled_xpath = '//span[contains(@class,"paging__pages--right")]//i[contains(@class,"lx-chevron-lrg-right")]'
    first_page_button_xpath = '//span[contains(@class,"paging--current") and normalize-space()="1"]'
    last_page_button_xpath = '//span[contains(@class,"paging__pages--right")]/preceding-sibling::span[1]'
    selected_page_xpath = '//span[contains(@class,"paging--current")]'

