class LocatorsDeviceProfile:
    device_serial_number_xpath = '//cdk-cell[contains(@class, "cdk-column-Device")]//span/a'
    admin_device_profile_title_xpath = '(//*[@class="device-profile__header__text"])'
    device_profile_device_header_xpath = '//div[contains(@class, "device-serial__container")]//span[normalize-space()="Device"]'
    device_profile_device_type_header_xpath = '(//*[text()=" Device Type "])[1]'
    device_profile_group_header_xpath = '(//*[text()=" Group "])[1]'
    device_profile_status_header_xpath = '(//*[text()=" Status "])[1]'
    device_profile_health_header_xpath = '//*[@id="health-title"]'
    device_profile_last_communicated_header_xpath = '(//*[text()=" Last Communicated "])[1]'
    device_profile_last_movement_header_xpath = '(//*[text()=" Last Movement "])[1]'
    device_profile_initial_connection_header_xpath = '(//*[text()=" Initial Connection "])[1]'
    device_profile_last_communicated_date = '//*[@id="device-info__last-connected"]//div[2]'
    request_new_image_xpath = '//span[text()="Request New Image"]'
    click_request_new_image_disabled_xpath = '//button[@id="request-image" and @disabled]'
    request_new_image_error = '//span[contains(text(), "Unable to retrieve new image")]'
    get_new_time_for_updated_image_xpath = '//*[@id="last-updated-info"]/div/div[2]'
    request_image_spinner_xpath = '//div[@class="request-image-spinner"]'
