class LocatorsDashboard:
    # Dashboard page Objects
    xml_text_content_attribute = 'textContent'

    # Tasks
    tasks_tab_xpath = "//div[@class='navigation']//*[contains(text(),'Tasks')]"
    coaching_tab_xpath = '//div[@class="navigation__item__subs-item-text-routed" and text()=" Due For Coaching "]'
    coaching_event_css = 'body > app > shell > div > div > div > ' \
                         'coaching-task-card-list > task-card-list > div > ' \
                         'div.ltc-list__content > coaching-task-card:nth-child(1)' \
                         ' > div > div.ltc-list__item__content > ' \
                         'div.ltc-list__item__content__footer > button'
    coaching_event_xpath = '//*[@class="ltc-list__item__content__footer__btn__text"]'
    assign_driver_xpath = '//div[@class="navigation__item__subs-item-text-routed" and text()=" Assign Drivers "]'

    # Library
    library_tab_xpath = '/html/body/app/shell/div/div/navigation/div[1]/div[4]/div/div[2]'
    events_tab_button_xpath = '/html/body/app/shell/div/div/navigation/div[1]/div[4]/div[2]/div[2]/div[1]/div'
    coaching_history_button_xpath = '/html/body/app/shell/div/div/navigation/div[1]' \
                                    '/div[4]/div[2]/div[2]/div[2]'
    recognition_history_button_xpath = '/html/body/app/shell/div/div/navigation' \
                                       '/div[1]/div[4]/div[2]/div[2]/div[3]'
    library_tab_xpath_new_ui = '//*[contains(@class, "lx-icon lx-lftnav-library")]'
    events_tab_button_xpath_new_ui = '//*[@href="#/driver-safety/library/events"]'
    coaching_history_button_xpath_new_ui = '//*[@href="#/driver-safety/library/coachinghistory"]'
    recognition_history_button_xpath_new_ui = '//*[@href="#/driver-safety/library/recognitions"]'
    driver_safety_text_id = 'driverSafetyText'

    # InsightsOpenTasks
    insights_tab_xpath = '/html/body/app/shell/div/div/navigation/div[1]/div[3]'
    open_tasks_report_tab_xpath = '//div[contains(text(), "Open Tasks Report")]'
    insights_tab_xpath_new_ui = '//*[normalize-space(text())="Insights"]'
    open_tasks_report_tab_xpath_new_ui = '//*[@href="#/driver-safety/insights/opentasksreport"]'

    # InsightsDriversReport
    drivers_report_tab_xpath = '//div[contains(text(), "Drivers Report")]'
    behaviors_report_tab_xpath = '//div[contains(text(), "Behaviors Report")]'
    group_report_tab_xpath = '//div[text()=" Group Report "]'
    coaches_report_tab_xpath = '//div[contains(text(), "Coaches Report")]'
    program_status_report_tab_xpath = '//div[contains(text(), "Program Status Report")]'
    driver_profile_link_xpath = '(//drivers-score-widget//*[@class="sum-table--linkable"])[1]'
    close_alert_link_xpath = '//*[@id="wm-shoutout-395244"]/div[1]'

    # HomePage
    home_tab_xpath = '/html/body/app/shell/div/div/navigation' \
                     '/div[1]/div[1]/div'
    home_tab_xpath_new_ui = '//span[@class="menu-text" and normalize-space()="Home"]'
    no_of_drivers_text_xpath = '//div[contains(@class, "title__count--value--success")]'
    no_of_drivers_count_xpath = '/html/body/app/shell/div/div/div/ng-component/driver-safety-dashboard/div/div[1]/filter-bar/div/div[2]/div[1]/div[1]/div/div[1]/div'
    no_of_drivers_count_xpath_newui = '//*[@data-test-id="filter-headerBar-countValue"]//*[contains(@class,"count--value--success")]'
    unassigned_drivers_text_xpath = '//*[@data-test-id="assignDriver-task-count"]'
    unassigned_drivers_count_xpath = '(//*[@id="unassignedDriver"]/div/div/div)[1]'
    due_for_coaching_text_xpath = '//*[@id="dueForCoaching"]/div/div/div[2]'
    due_for_coaching_count_xpath = '//*[@id="dueForCoaching"]/div/div/div'
    fyi_notify_text_xpath = '//*[@id="fyiNotify"]/div/div/div[2]'
    fyi_notify_count_xpath = '//*[@id="fyiNotify"]/div/div/div'
    collisions_text_xpath = '//*[@id="collisions"]/div/div/div[2]'
    collisions_count_xpath = '//*[@id="collisions"]/div/div/div'
    possible_collisions_text_xpath = '//*[@id="possibleCollisions"]/div/div/div[2]'
    possible_collisions_count_xpath = '//*[@id="possibleCollisions"]/div/div/div'
    assign_driver_title_text_xpath = '//*[@class="filter-header-title"]'
    due_for_coaching_title_text_xpath = '//*[text()="Due for Coaching"]'
    fyi_notify_title_text_xpath = '//*[text()="Fyi Notify"]'
    collisions_title_text_xpath = '//*[text()="Collisions"]'
    possible_collisions_title_text_xpath = '/html/body/app/shell/div/div/div/' \
                                           'collision-task-card-list/task-card-list' \
                                           '/div/div[1]/filter-bar/div/div[1]/span[1]'
    groups_by_highest_score_text_xpath = '//*[contains(text(), "Groups by Highest Score")]  '
    group_text_xpath = '//span[text()="Group"]'
    coachable_score_text_xpath = '//groups-widget//span[text()="Coachable Score"]'
    group_widget_score_trend_text_xpath = '//groups-widget//span[text()="Trend"]'

    coachable_events_text_xpath = '//groups-widget//span[text()="Coachable Events"]'
    group_widget_event_trend_text_xpath = '//groups-widget//span[text()="Trend"]'
    coaches_by_lowest_effectiveness_text_xpath = '//*[contains(text(), "Coaches by Lowest Effectiveness")]'
    coach_text_xpath = '//span[text()="coach"]'
    coaching_effectiveness_text_xpath = '//span[text()="coaching effectiveness"]'
    avg_days_to_coach_text_xpath = '//span[text()="avg days to coach"]'
    coached_events_text_xpath = '//span[text()="coached events"]'
    with_notes_text_xpath = '//span[text()="with notes"]'
    drivers_by_highest_score_text_xpath = '//*[contains(text(), "Drivers by Highest Score")]'
    driver_text_xpath = '//drivers-score-widget//span[contains(text(), "Driver")]'
    driver_widget_coachable_score_text_xpath = '//drivers-score-widget//span[contains(text(), "Coachable Score")]'
    driver_widget_trend_text_xpath = '//drivers-score-widget//span[contains(text(), "Trend")]'
    impact_text_xpath = '//span[text()="Impact"]'
    behaviors_by_highest_frequency_xpath = '//*[contains(text(), "Behaviors by Highest Frequency")]'
    group_filter_button_xpath = '//*[@class="group-filter"]'
    group_filter_search_xpath = '//*[@placeholder="Search by Group"]'
    group_filter_select_search_xpath = ('/html/body/ngb-modal-window/div/div/group-selector-modal/group-selector/div'
                                        '/div[1]/div[2]/div/lytx-typeahead/div/ngb-typeahead-window/button')
    group_filter_done_button_xpath = '//*[text()="Done"]'
    date_filter_button_xpath = '//*[@class="lx-date-range-filter"]'
    from_date_select_xpath = '(//*[contains(@class,"custom-day") and text()=" 9 "])[1]'
    end_date_select_xpath = '(//*[contains(@class,"custom-day") and text()=" 9 "])[1]'
    apply_button_xpath = '//*[@id="btn-apply"]'
    view_details_behaviors_link_xpath = '//coachable-behaviors-widget//*[contains(text(),"View Details")]'
    view_details_groups_link_xpath = '//groups-widget//*[contains(text(),"View Details")]'
    view_details_coaches_link_xpath = '//coaches-widget//*[contains(text(),"View Details")]'
    view_details_drivers_link_xpath = '//drivers-score-widget//*[contains(text(),"View Details")]'
    no_of_tasks_xpath = '//div[contains(@class, "title__count--value--success")]'
    group_name_filtered_xpath = '(//groups-widget//*[contains(@class, "sum-table--linkable")])[1]'
    coach_name_filtered_xpath = '(//coaches-widget//*[contains(@class, "sum-table--linkable")])[1]'
    driver_name_filtered_xpath = '(//drivers-score-widget//*[contains(@class, "sum-table--linkable")])[1]'
    group_widget_1st_group_xpath = '(//groups-widget//*[contains(@class, "sum-table--linkable")])[1]'
    coach_widget_1st_coach_xpath = '(//coaches-widget//*[contains(@class, "sum-table--linkable")])[1]'
    driver_widget_1st_driver_xpath = '(//drivers-score-widget//*[contains(@class, "sum-table--linkable")])[1]'
    behavior_widget_1st_behavior_xpath = '//coachable-behaviors-widget//*[contains(@class, "sum-table--linkable")])[1]'
    behavior_widget_no_data_msg_xpath = '//*[text()=" There are no Behaviors to display. "]'
    reset_button_xpath = '//div[@class="reset-button-text"]'
    collisions_tab_xpath = '//div[@class="navigation__item__subs-item-text-routed" and text()=" Collisions "]'
    fyi_notify_tab_xpath = '//div[@class="navigation__item__subs-item-text-routed" and text()=" Fyi Notify "]'
    quick_search_tab_new_UI_xpath = '//*[text()=" Search "]'
    quick_search_tab_xpath = '(//*[text()="Search"])[1]'
    quick_search_text_box_xpath = '//*[@id="searchInput"]'
    search_icon_xpath = '(//*[@class="lx-icon lx-search"])[2]'
    preview_searched_event_xpath = '//*[@id="event-preview-container"]/div[1]/span[2]/span'
    close_preview_video_id = 'close-modal-icon_after-load'
    admin_tab_id = "adminText"
    video_search_tab_id = "videoSearchText"
    fleet_tracking_tab_id = 'fleetTrackingText'
    dvir_tab_id = 'dvirText'
    hos_tab_id = 'eldText'
    compliance_services_tab_id = 'rairText'
    lab_tab_id = 'labText'
    Behaviors_list = '//coachable-behaviors-widget//lx-section-content/div/div/div/sum-table/div/div[2]/div[1]/div'
    tasks_label_xpath = '/html/body/app/shell/div/div/div/ng-component/driver-safety-dashboard/' \
                        'div/task-counts/div/div[1]/span'
    tasks_label_new_UI_xpath = '//*[contains(@class, "insights-tasks-header-title")]'
    metrics_label_xpath = '/html/body/app/shell/div/div/div/ng-component/driver-safety-dashboard/div/div[2]/div[1]'
    metrics_label_new_UI_xpath = '//*[contains(@class, "driver-safety-dashboard--metrics__title")]'

    app_title = '//span[@class="title"]'
    safe_driving_trend_text_xpath = '//*[contains(text(), "Safe Driving Trend")]'
    safe_driving_trend_graph_class = 'lx-line-chart'
    groups_by_highest_perc_safe_drivers_xpath = '//*[contains(text(),"Groups by Highest % Safe Drivers")]'
    group_text_for_safe_drive_report_widget_xpath = '//span[text()="group"]'
    safe_drivers_xpath = '//*[text()="% safe drivers"]'
    eligible_for_recognition_text_xpath = '//*[text()="eligible for recognition"]'
    recognized_xpath = '//*[text()="eligible for recognition"]/parent::div/following-sibling::div/span'
    safe_drivers_report_tab = '//div[contains(text(),"Safe Driving Report")]'
    safe_drive_widget_first_group_xpath = '//*[@class="safe-driving-trend"]//*[@class="sum-table--linkable"]'
    recognize_button_xpath = '//*[text()="Recognize Drivers"]'

    fleet_telematics_tab = 'telematicsText'
    library_menu_xpath = '//*[text()=" Library "]'
    home_menu_xpath = '//*[text()=" Home "]'
    insights_menu_xpath = '//*[text()=" Insights "]'
    recognitions_submenu_xpath = ''
    events_submenu_xpath = '//*[text()=" Events"]'
    recognition_history_submenu_xpath = '//*[text()=" Recognition History"]'
    coaching_history_submenu_xpath = '//*[text()=" Coaching History"]'
    data_export_submenu_xpath = '//*[text()=" Data Export"]'
    open_tasks_report_submenu_xpath = '//*[text()=" Open Tasks Report"]'
    drivers_report_submenu_xpath = '//*[text()=" Drivers Report"]'
    group_report_submenu_xpath = '//*[text()=" Group Report"]'
    coaches_report_submenu_xpath = '//*[text()=" Coaches Report"]'
    program_status_report_submenu_xpath = '//*[text()=" Program Status Report"]'
    behaviors_report_submenu_xpath = '//*[text()=" Behaviors Report"]'
    collision_link_xpath = '//*[@monitorclick="InsightsTaskCountsComponent.CollisionsLink"]'
    collision_title_xpath = '//*[text()="Collisions"]'
    data_export_tab_xpath = '/html/body/app/shell/div/div/navigation/div[1]' \
                            '/div[4]/div[2]/div[2]/div[4]'
    lytx_geotab_logo_xpath = '//*[@class="logo-container__lytx_geotab_logo"]'
    driver_widget_no_data_msg_xpath = '//*[contains(text(),"There are no Drivers to display")]'
    lytx_logo_xpath = '//*[@class="logo-container__logo"]'
    lytx_logo_old_ui_xpath = '/html/body/app-root/div[1]/img | //div[contains(@class, "header-left__logo")] | //div[contains(@class, "logo-container__logo")]'
    eld_error_msg_xpath = '//*[@class="inline-error-message"]'
    eld_frame_class = 'eldFrame'


