class LocatorsSafeDrivingReport:
    safe_driving_page_title_xpath = '//h1[text()="Safe Driving Report"]'
    driver_text_xpath = '//*[text()="Driver"]'
    group_text_xpath = '//*[text()="Group"]'
    distance_driven_text_xpath = '//*[text()="Distance Driven"]'
    achievement_text_xpath = '//*[text()="Achievement"]'
    non_coachable_behaviors_text_xpath = '//*[text()="Non-Coachable Behaviors"]'
    group_filter_xpath = '//*[text()=" Filter By Group "]'
    input_group_name_xpath = '//input[@placeholder="Search by Group"]'
    select_group_from_dropdown_xpath = '//button[@class="dropdown-item"]'
    click_done_xpath = '//span[text()="Done"]'
    click_quarter_filter_ID = 'period-filter'
    first_quarter_xpath = '(//li/span)[1]'
    click_include_exclude_filter_ID = 'behavior-inclusion-filter'
    select_include_behaviors_xpath = '//li//*[text()=" Include Drivers with Behaviors "]'
    search_driver_input_box_xpath = '//input[@placeholder="Search Name or ID"]'
    select_first_driver = '//*[@id="driver-filter"]//button'
    group_page_text_xpath = '//button[@class="lx-btn-small lx-btn-text lytx-tab active"]'
    filtered_group_name_xpath = '//span[@class="group-filter__label"]'
    reset_buton_xpath = '//*[text()="Reset"]'
    tool_tip_icon_xpath = '//*[@class="lytx-info-icon"]'
    driver_count_tool_tip_xpath = '//ngb-tooltip-window'
    verbiage_text_xpath = '//div[@class="disclaimer"]'
    achievement_icon_text_xpath = '//img[@class="achievement-icon"]'
    achievement_icon_hover_text_xpath = '//*[@class="lytx-tooltip-content"]'
