class LocatorsRiskCompany:
    # Dashboardpage
    dashboard_text_xpath = '//*[text()="Dashboard"]'
    drivers_by_highest_text_score_text_xpath = '//*[contains(text(), "Drivers by Highest Score")]'
    categories_by_highest_frequency_text_xpath = '//*[contains(text(), "Categories by Highest Frequency")]'
    driver_count_xpath = '//span[contains(text(), "Driver")]/parent::div/preceding-sibling::div'
    group_filter_xpath = '//*[@class="group-filter"]'
    search_group_filter_textbox_xpath = '//*[@placeholder="Search by Group"]'
    select_searched_group_filter_xpath = '//*[contains(@class, "dropdown-item")]//*[contains(text(),"Vehicle")]'
    done_button_group_filter_xpath = '//*[text()="Done"]'
    date_filter_xpath = '//*[contains(@class, "lx-date-range-filter")]'
    select_date1_button_xpath = '(//ngb-datepicker-month//*[text()=" 7 "])[1]'
    select_date2_button_xpath = '(//ngb-datepicker-month//*[text()=" 13 "])[1]'
    apply_date_filter_xpath = '//*[text()="Apply"]'
    view_detail_xpath = '//*[text()="View Details"]'
    reset_button_xpath = '//*[text()="Reset"]'
    home_tab_xpath = '(//*[text()="Home"])[1]'
    insight_tab_xpath = '(//*[text()="Insights"])[1]'
    insight_tab_new_ui_xpath = '//*[normalize-space(text())="Insights"]'
    drivers_report_tab_xpath = '(//*[text()=" Drivers Report "])[1]'
    drivers_report_new_ui_xpath = '//*[normalize-space(text())="Drivers Report"]'
    drivers_report_title_xpath = '(//*[text()="DRIVERS REPORT"])[1]'
    driver_scores_title_xpath = '(//*[@class="tab-text"])[1]'
    continual_behaviors_title_xpath = '(//*[@class="tab-text"])[2]'
    alerts_title_xpath = '(//*[@class="tab-text"])[3]'
    driver_title_xpath = '(//*[@class="report-sorting-container__label"])[1] '
    group_title_xpath = '(//*[@class="report-sorting-container__label"])[2]'
    score_title_xpath = '(//*[@class="sub-header-title"])[1]'
    events_title_xpath = '(//*[@class="sub-header-title"])[2]'
    recent_notes_title_xpath = '(//*[@class="report-sorting-container__label"])[3]'
    categories_filter_button_xpath = '//*[@placeholder="Categories"]'
    select_categories_filter_xpath = '//multiselect-highlight[text()="Accelerating"]'
    home_tab_xpath_new_ui = '//span[@class="menu-text" and normalize-space()="Home"]'
