class LocatorsEditVehiclePage:
    vehicle_name_textbox_xpath = '//*[@id="vehicleName"]'
    save_edit_vehicle_button_xpath = '//*[@id="submitButton"]'
    delete_button_in_edit_vehicle_page = '//*[text()="Delete"]'
    delete_vehicle_continue_button = '//*[text()=" Continue "]'
    continue_alert_xpath = '(.//*[normalize-space(.)="Continue"])[1]'
    dvir_access_status_xpath = '(//span[text()=" Enabled " or text()=" Disabled "])[1]'
    assign_device_textbox_xpath = '//input[@placeholder="Search for a device"]'
    select_searched_device_xpath = '//button[@role="option"]//span[contains(@class, "dropdown-item__left")]'
    search_cancel_xpath = './/*[@class="lx-icon lx-close-x"]'
    search_magnifier_xpath = '//input[@placeholder="Search for a device"]/following-sibling::span'
    continual_button_id = 'modalShellPrimaryButton'
    status_filter_xpath = '//*[@id="status"]//i'
    status_filter_in_service_xpath = '//span[text()=" In Service "]'
    update_vehicle_success_message_xpath = '//*[contains(text(), "successfully updated.")]'
