class LocatorsFleetTelematicsLeftPanelOldUI:
    iframe_class = 'telematicsFrame'
    telematicsLoaded_xpath = '//*[@class="telematicsLoaded"]'
    more_charts_button = 'dashboard_MoreCharts'
    lytx_geotab_logo_xpath = '//*[@class="logo-container__lytx_geotab_logo"]'
    left_navigation_expand_mode_xpath = '//*[@class="left-navigation expanded"]'
    left_navigation_collapse_mode_xpath = '//*[@class="left-navigation collapsed"]'
    arrow_left_direction = '//button[@class="toggle-btn" and "lx-icon lx-arrow-forward rotate-180"]'
    arrow_right_direction = '//*[@class="lx-icon lx-arrow-forward"]'

    # Menu's in left navigation expand mode
    dashboard_menu_xpath = '//*[@class="navigation__item__left"][1]'
    map_menu_xpath = '//div[text()="Map"]'
    productivity_menu_xpath = '//div[text()="Prod."]'
    compliance_menu_xpath = '//div[text()="Comp."]'
    maintenance_menu_xpath = '//div[text()="Maint."]'
    sustainability_menu_xpath = '//div[contains(text(),"Sust")]'
    reports_menu_xpath = '//div[contains(text(),"Insights")]'
    rulesandexceptions_menu_xpath = '//div[contains(text(),"Rules")]'
    messages_menu_xpath = '//div[contains(text(),"Messages")]'
    notifications_menu_xpath = '//div[contains(text(),"Notifications")]'
    config_menu_xpath = '//div[contains(text(),"config")]'
    addins_menu_xpath = '//div[contains(text(),"Addins")]'
    marketplace_menu_xpath = '//div[contains(text(),"Marketplace")]'

    # Productivity sub-menus and their sub-child links
    triphistory_submenu_xpath = '//div[contains(text(), "Trip History")]'
    routes_submenu_xpath = '//div[contains(text(), "Routes")]'
    plannedvsactualroutes_subchild_xpath = '//div[contains(text(), "Planned vs Actual Routes")]'
    routesummary_subchild_xpath = '//div[contains(text(), "Route Summary")]'
    unmatchedroute_subchild_xpath = '//div[contains(text(), "Unmatched Route")]'
    importroutes_subchild_xpath = '//div[contains(text(), "Import Routes")]'
    publicworks_submenu_xpath = '//*[text()=" Public Works"]'
    routecompletion_subchild_xpath = '//div[contains(text(), "Route Completion")]'
    materialmanagement_subchild_xpath = '//div[contains(text(), "Material Management")]'
    zones_submenu_xpath = '//*[contains(text(),"Zones")]'
    zones_subchild_xpath = '//*[@href="#/fleet-telematics/productivity/zones"]'
    zonetypes_subchild_xpath = '//*[contains(text(), "Zone Types")]'
    zonevisits_subchild_xpath = '//*[contains(text(), "Zone Visits")]'
    importzones_subchild_xpath = '//*[contains(text(), "Import Zones")]'
    drivercongregation_submenu_xpath = '//div[contains(text(),"Driver Congregation")]'
    assetlocationsharing_submenu_xpath = '//div[contains(text(),"Asset Location Sharing")]'
    linkedassets_submenu_xpath = '//div[contains(text(),"Linked Assets")]'
    riskmanagement_submenu_xpath = '//div[contains(text(),"Risk Management")]'
    productivity_menu_dropdown_xpath = '//div[text()="Prod."]'
    routes_submenu_dropdown_xpath = '//*[text()=" Routes"]//preceding::*[@class="lx-icon lx-sm-chevron-right"]'
    routes_subchild_xpath = '//*[@class="subchild-link" and text()=" Routes "]'
    publicworks_submenu_dropdown_xpath = '(//*[text()=" Public Works"]//preceding::*[@class="lx-icon lx-sm-chevron-right"])[last()]'
    zones_submenu_dropdown_xpath = '(//*[text()=" Zones"]//preceding::*[@class="lx-icon lx-sm-chevron-right"])[last()]'

    # Compliance sub-menus and their sub-child links
    compliance_menu_dropdown_xpath = '//*[text()=" Compliance "]'
    hos_submenu_xpath = '//div[text()=" Hos Logs "]'
    logs_xpath = '//*[@href="#/fleet-telematics/compliance/hoslogs"]'
    hos_submenu_dropdown_xpath = '//*[text()=" HOS"]//preceding::*[@class="lx-icon lx-sm-chevron-right"]'
    unidentified_driving_subchild_xpath = '//div[text()=" Unidentified Driving "]'
    violations_subchild_xpath = '//div[text()=" Violations "]'
    availability_subchild_xpath = '//div[text()=" Availability "]'
    timecardreport_submenu_xpath= '//div[text()=" Time Card Report "]'
    iftareport_submenu_xpath = '//div[text()=" IFTA Report "]'
    cleantruckcheck_submenu_xpath = '//div[text()=" Clean Truck Check "]'

    # Maintenance sub-menus and their sub-child links
    assetinspection_submenu_xpath = '//div[contains(text(),"Asset Inspection")]'
    diagnostic_measurements_submenu_xpath = '//div[contains(text(),"Diagnostic Measurements")]'
    reminders_submenu_xpath = '//*[@href= "#/fleet-telematics/maintenance/reminders"]'
    faults_subchild_xpath = '//div[contains(text(),"Faults")]'
    measurements_subchild_xpath = '//*[@href = "#/fleet-telematics/maintenance/measurements"]'
    maintenance_center_sub_menu_xpath = '//span[@class="subitem-text"]/*[contains(text(), "Maintenance Center")]'
    speed_profile_subchild_xpath = '//div[contains(text(),"Speed Profile")]'
    Log_data_and_collisions_subchild_xpath = '//div[contains(text(),"Log Data and Collisions")]'
    work_order_sub_child_xpath = '//div[contains(text(),"Work Order")]'
    schedules_sub_child_xpath = '//div[contains(text(),"Schedules")]'


    # Sustainability sub-menus and their sub-child links
    sustainabilitycenter_submenu_xpath = '//div[contains(text(),"Sustainability Center")]'
    fuel_energy_usage_submenu_xpath = '//div[contains(text(),"Fuel and EV Energy Usage")]'
    evbatteryhealth_submenu_xpath = '//div[contains(text(),"EV Battery Health")]'
    evcharginghistory_submenu_xpath = '//div[contains(text(),"EV Charging")]'
    bevrangecapability_submenu_xpath = '//div[contains(text(),"BEV Range Capability")]'

    # Reports sub-menus and their sub-child links
    reports_menu_dropdown_xpath = '//*[text()=" Reports "]//following-sibling::*[@class="arrow"]'
    myreports_submenu_xpath = '//div[contains(text(),"My Reports")]'
    reportsetup_submenu_xpath = '//div[contains(text(),"Reports Setup")]'
    dashboard_subchild_xpath = '//*[@class = "subchild-link" and text() = " Dashboard "]'
    reportviews_subchild_xpath = '//*[@class = "subchild-link" and text() = " Report Views "]'
    emailedreports_subchild_xpath = '//*[@class = "subchild-link" and text() = " Emailed Reports "]'

    # Rules & Exceptions sub-menus and their sub-child links
    rules_submenu_xpath = '//div[contains(text()," Rules")]'
    exceptions_submenu_xpath = '//div[contains(text()," Exceptions")]'
    rulesandexceptions_menu_dropdown_xpath = '//*[text()=" Rules & Exceptions "]//following-sibling::*[@class="arrow"]'

    # Config sub-menus and their sub-child links
    fleet_settings_submenu_xpath = '//div[contains(text(),"Settings")]'
    work_hours_submenu_xpath = '//div[contains(text(),"Work Hours")]'
    holidays_submenu_xpath = '//div[contains(text(),"Holidays")]'
    audit_log_submenu_xpath = '//div[contains(text(),"Audit Log")]'

    # Driver Safety
    fyinotify_submenu_xpath = '//*[@href="#/driver-safety/tasks/fyinotify"]'
    collisions_submenu_xpath = '//*[@href="#/driver-safety/tasks/collision"]'
    due_for_coaching_submenu_xpath = '//*[@href="#/driver-safety/tasks/coaching"]'
    assign_drivers_submenu_xpath = '//*[@href="#/driver-safety/tasks/assigndriver"]'
    insights_menu_xpath = '//*[text()=" Insights "]'
    open_tasks_report_submenu_xpath = '//*[@href="#/driver-safety/insights/opentasksreport"]'
    drivers_report_submenu_xpath = '//*[@href="#/driver-safety/insights/driversreport"]'
    group_report_submenu_xpath = '//*[@href="#/driver-safety/insights/groupreport"]'
    coaches_report_submenu_xpath = '//*[@href="#/driver-safety/insights/coachesreport"]'
    program_status_report_submenu_xpath = '//*[@href="#/driver-safety/insights/programstatusreport"]'
    behaviors_report_submenu_xpath = '//*[@href="#/driver-safety/insights/behaviorsreport"]'
    library_menu_xpath = '//*[text()=" Library "]'
    events_submenu_xpath = '//*[@href="#/driver-safety/library/events"]'
    coachinghistory_submenu_xpath = '//*[@href="#/driver-safety/library/coachinghistory"]'
    recognitionhistory_submenu_xpath = '//*[@href="#/driver-safety/library/recognitions"]'
    dataexport_submenu_xpath = '//*[@href="#/driver-safety/library/dataexport"]'
    search_submenu_xpath_old_ui = '//*[text()="Search"]'

    # Video Search
    vehicles_menu_xpath = '//*[@class="menu-text" and text()=" Vehicles "]'
    map_search_menu_xpath = '//*[@class="menu-text" and text()=" Map Search "]'
    vs_library_menu_xpath = '//*[@class="menu-text" and text()=" Library "]'
    saved_videos_submenu_xpath = '//*[@href = "#/lvs/library/saved"]'
    video_tags_submenu_xpath = '//*[@href = "#/lvs/library/tagged"]'

    # Admin
    users_menu_xpath = '//*[@class="menu-text" and normalize-space()="Users"]'
    admin_vehicles_menu_xpath = '//*[@class="menu-text" and normalize-space()="Vehicles"]'
    telematics_assets_menu_xpath = '//*[@class="menu-text" and normalize-space()="Telematics Assets"]'
    telematics_assets_menu_xpath_old_ui = '//*[text()="Telematics Assets"]'
    devices_menu_xpath = '//*[@class="menu-text" and normalize-space()="Devices"]'
    geofences_menu_xpath = '//*[@class="menu-text" and normalize-space()="Geofences"]'
    admin_insights_menu_xpath = '//*[@class="menu-text" and normalize-space()="Insights"]'
    insights_driver_id_menu_xpath = '//*[@href = "#/admin/insights/driverid"]'
    config_settings_menu_xpath = '//*[@class="menu-text" and normalize-space()="Config. Settings"]'
