class FleetUtilizationReport:
    fleet_utilization_tab_xpath = '(//*[text()=" Fleet Utilization [Beta] "])[1]'
    fleet_utilization_text_xpath = '//*[text()="Fleet Utilization"]'
    distance_tab_xpath = '//*[text()="Distance"]'
    date_filter_xpath = '//*[@class="lx-date-range-filter"]'
    fleet_utilization_date_range_start_month_xpath = '(//*[@class="date month ng-untouched ng-pristine ng-valid"])[1]'
    fleet_utilization_date_range_start_day_xpath = '(//*[@class="date day ng-untouched ng-pristine ng-valid"])[1]'
    fleet_utilization_date_range_start_year_xpath = '(//*[@class="date year ng-untouched ng-pristine ng-valid"])[1]'
    fleet_utilization_date_range_end_month_xpath = '/html/body/app-root/shell/div/div/div/app-utilization-report/div/div[1]/filter-bar/div/div[2]/div[2]/lx-date-range-filter/div/div[2]/lx-date-range-selector/div/div[1]/div[2]/div[2]/lx-date-input/div/input[1]'
    fleet_utilization_date_range_end_day_xpath = '/html/body/app-root/shell/div/div/div/app-utilization-report/div/div[1]/filter-bar/div/div[2]/div[2]/lx-date-range-filter/div/div[2]/lx-date-range-selector/div/div[1]/div[2]/div[2]/lx-date-input/div/input[2]'
    fleet_utilization_date_range_end_year_xpath = '/html/body/app-root/shell/div/div/div/app-utilization-report/div/div[1]/filter-bar/div/div[2]/div[2]/lx-date-range-filter/div/div[2]/lx-date-range-selector/div/div[1]/div[2]/div[2]/lx-date-input/div/input[3]'
    date_filter_apply_button_xpath = '//*[@id="btn-apply"]'
    get_group_row_count_xpath = '//*[@id="distance-by-group-widget"]//*[@class="sum-table--values"]'
    get_vehicle_row_count_xpath = '//*[@id="distance-by-vehicle-widget"]//*[@class="sum-table--values"]'
    distance_trend_graph_xpath = '//*[@class="lytx-trends__chart"]'
    group_filter_xpath = '//*[@class="group-filter"]'
    search_by_group_textbox_xpath = '//*[@placeholder="Search by Group"]'
    select_search_button_xpath = '//*[@class="dropdown-item active"]'
    done_button_xpath = '//*[@class="group-selector-bottom-done lx-btn lx-btn-primary"]'
    average_distance_text_xpath = '//*[text()="Average Distance (mi)"]'
    distance_group_text_xpath = '//*[text()="Distance By Group"]'
    distance_vehicle_text_xpath = '//*[text()="Distance By Vehicle"]'
    reset_button_xpath = '//*[@class ="lx-btn lx-btn-text filter-header-bar__filters--reset"]'
    group_widget_view_details_xpath = '(//*[@class="common-widget__header__right"])[1]'
    fleet_operations_title_id = 'fleetOperationsTitle'
    groups_tab_text_xpath = '/html/body/app-root/shell/div/div/div/app-fleet-operations/div/div[2]/lytx-tab-views/div/div[1]/button[1]/span'
    vehicle_widget_view_details_xpath = '(//*[@class="common-widget__header__right"])[2]'
    vehicle_tab_text_xpath = '/html/body/app-root/shell/div/div/div/app-fleet-operations/div/div[2]/lytx-tab-views/div/div[1]/button[2]/span'
    vehicle_name_xpath = '(//*[@class="sum-table--linkable"])[2]'
    vehicle_profile_text_title_xpath = '/html/body/app-root/shell/div/div/div/app-vehicle-profile/div/div[1]'
    group_name_xpath = '(//*[@class="sum-table--linkable"])[1]'
    fleet_operation_group_filter_text_xpath = '//*[@class="group-filter__label" and text()=" SF400 Kam-Way Alpha Trial "]'
    engine_hours_tab_xpath = '//*[text()="Engine Hours"]'
    engine_hours_trend_text_xpath = '//*[text()="Average Engine Hours (hrs)"]'
    engine_hours_group_text_xpath = '//*[text()="Engine Hours by Group"]'
    engine_hours_vehicle_text_xpath = '//*[text()="Engine Hours by Vehicle"]'
    engine_hours_group_row_count_xpath = '//*[@id="engine-hours-by-group-widget"]//*[@class="sum-table--values"]'
    engine_hours_vehicle_row_count_xpath = '//*[@id="engine-hours-by-vehicle-widget"]//*[@class="sum-table--values"]'
    engine_hours_trend_graph_xpath = '//*[@class="engine-hours-trends"]'
    engine_fleet_operation_group_filter_text_xpath = '//*[@class="group-filter__label" and text()=" SF500 Alpha Trial "]'
    group_column_name_title_of_group_widget_xpath = '(//*[text()="Group"])[1]'
    total_vehicle_column_name_title_of_group_widget_xpath = '//*[text()="Total Vehicles"]'
    total_column_name_title_of_group_widget_xpath = '(//*[text()="Total"])[1]'
    avg_day_column_name_title_of_group_widget_xpath = '(//*[text()="Avg/Day"])[1]'
    vehicle_column_name_title_of_vehicle_widget_xpath = '//*[text()="Vehicle"]'
    group_column_name_title_of_vehicle_widget_xpath = '(//*[text()="Group"])[2]'
    total_column_name_title_of_vehicle_widget_xpath = '(//*[text()="Total"])[2]'
    avg_day_column_name_title_of_vehicle_widget_xpath = '(//*[text()="Avg/Day"])[2]'


