class LocatorAdminGroups:
    groups_tab_xpath = '//*[contains(text(), "Groups")]'
    groups_tab_header_xpath = '//*[text()="Group Management"]'
    groups_tab_count_xpath = '//*[@class="filter-header-bar__title__count"]'
    group_count_xpath = '//*[@class="filter-header-bar__title__count--container"]//div[1]'
    first_group_xpath = '//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]'
    plus_icon_xpath = '//app-group-hierarchy//span[text()="Add group"]/preceding-sibling::img'
    plus_icon_child_xpath = '(//app-group-hierarchy//span[text()="Add group"]/preceding-sibling::img)[2]'
    add_group_pop_up_xpath = '(//div[@class="modal-dialog"]//div)[1]'
    group_name_field_in_pop_up_xpath = '//*[text()="Group Name"]'
    group_path_field_in_pop_up_xpath = '//*[contains(text(), "Group Path")]'
    group_path_field_in_delete_pop_up_xpath = '//*[@class="delete-group-container"]//*[contains(text(), "Group Path")]'
    get_description_field_in_pop_up_xpath = '//*[text()="description"]'
    create_or_save_button_disabled_xpath = '//button[@disabled]'
    group_name_input_xpath = '//input[@id="groupNameValue"]'
    description_input_xpath = '//*[@id="descriptionValue"]'
    create_or_save_group_button_xpath = '//button[@type="submit"]'
    cancel_xpath = '//button[contains(text(), "Cancel")]'
    group_created_alert_msg_xpath = '//div[@aria-label="Success – Group added."]'
    group_already_exists_error_msg_xpath = '//*[@aria-label="Error! Group already exists with same Name and ParentId."]'
    new_created_group_name_xpath = '//*[@title="Automation_Group1" or @title="Auto_modified_group"]'
    group_description_from_group_container_xpath = '//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//div[@class="card-footer"]'
    number_of_subgroups_xpath = '//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]//div[@class="card-details"]'
    kebab_button_child_group_xpath = '//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//div[contains(@class, "kebab-menu")]'
    parent_group_xpath = '(//div[@class="node-card-wrapper"])[1]//div[@class="card-header"]'
    parent_group_kebab_menu_xpath = '(//div[@class="node-card-wrapper"])[1]//div[@class="card-header"]//div[contains(@class, "kebab-menu")]'
    edit_option_xpath = '//li/span[text()="Edit"]'
    move_option_xpath = '//li/span[text()="Move"]'
    delete_option_xpath = '//li/span[text()="Delete"]'
    delete_edit_page_xpath = '//*[text()="Delete"]'
    delete_group_pop_up_xpath = '//*[@class="delete-group-container"]//button[contains(text(),"Delete")]'
    cancel_in_delete_pop_up_xpath = '//*[@class="delete-group-container"]//button[contains(text(), "Cancel")]'
    number_of_sub_groups_for_first_child_group_xpath = '(//div[1]/following-sibling::div//div[@class="current-level"]/div)[1]//*[@class="card-details"]'
    edit_group_pop_up_title_xpath = '(//div[@class="modal-dialog"]//div)[1]//*[text()="Edit Group"]'
    sub_groups_field_in_pop_up_xpath = '//*[text()=" Subgroups "]'
    group_name_require_xpath = '//*[@class="group-input__label required"]'
    first_current_level_sibling_group_name_xpath = '(//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//span)[1]'
    second_current_level_group_name_xpath = '//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//div[@class="next-level-wrapper"][1]//span'
    first_child_group_xpath = '(//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//div[@class="current-level"]/div)[1]'
    delete_group_pop_up_title_xpath = '//*[contains(text(),"Delete Group:")]'
    confirmation_msg_for_delete_group_xpath = '//*[@class="confirmation-message"]/p'
    group_deleted_alert_msg_xpath = '//*[@role="alertdialog"]'
    cant_delete_group_message_xpath = '//span[contains(text(), "Can’t Delete Group:")]'
    get_cant_delete_group_suggestion_message_xpath = '//*[contains(@class, "non-deletable-content")]//p'
    close_button_xpath = '//*[text()="Close"]'
    search_box_input_xpath = '//input[@placeholder="Search Groups"]'
    search_box_drop_down_menu_xpath = '//*[contains(@class, "dropdown-menu")]'
    selected_group_xpath = '//span[text()="Cellular Unassigned"]/ancestor::div[@class="selected-card-container"]'
    subgroups_xpath = '//div[contains(@class,"independent-child-list")]'
    doughnut_peddler_group_text_xpath = '//span[text()="The Doughnut Peddler, LLC- Main"]'
    distribution_centre_group_text_xpath = '//span[text()="Distribution Centers"]'
    breadcrumb_text_xpath = '//div[contains(@class, "group-path")]'
    group_hierarchy_xpath = '//div[@class="group-flowchart"]'
    group_card_details_xpath = '//div[@class="card-details"]'
    search_group_box_xpath = '//input[@placeholder="Search Groups"]'
    download_csv_xpath = '//*[@id="csv-button"]'
    import_group_button_xpath = '//*[@id="import-groups-button"]'
    kebab_second_tier_child_xpath = '(//div[@class="child-node-wrapper"]/div[@class="node"][1]/div[1]/following-sibling::div//div[contains(@class, "kebab-menu")])[2]'

    # Audit Logs - View Change History
    view_change_history_xpath = '//*[@ngbtooltip="View Change History"]'
    name_table_text_xpath = '//cdk-header-cell//span[contains(text(),"Name")]'
    groups_table_text_xpath = '//cdk-header-cell//span[contains(text(),"Group")]'
    action_table_text_xpath = '(//cdk-header-cell//span[contains(text(), "Action")])[1]'
    action_details_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Action Details")]'
    editor_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Editor")]'
    action_date_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Action Date")]'
    group_audit_log_title_xpath = '//*[contains(text(),"Group Audit Log")]'
    search_group_textbox_xpath = '//*[@id="searchInput"]'
    date_filter_xpath = '//*[@class="audit-date"]'
    select_date_range_today_xpath = '//*[@class="audit-date"]//span[contains(@class, "today")]'
    select_actions_filter_xpath = '//*[@class="audit-actions"]'
    download_log_button_xpath = '//*[contains(text(),"Download Log")]'
    download_log_confirm_button_xpath = '//*[@id="modalShellPrimaryButton"]'
    download_log_button_disabled_xpath = '//*[@class="audit-download"]//button[@disabled]'
    first_group_affected_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[2]/span[2]'
    no_audit_logs_message_xpath = '//*[contains(@class,"lx-table__table__empty-message")]'
    action_date_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[5]'
    close_view_change_history_xpath = '//*[text()=" Close "]'
    view_change_history_popup_xpath = '//*[@modalcomponentname="GroupAuditLog"]'
    reset_button_audit_page_xpath = '//*[@class="audit-log-modal-shell"]//*[text()="Reset"]'
    select_added_xpath = '//li/span[contains(text(), "Added")]'
    select_edited_xpath = '//li/span[contains(text(), "Edited")]'
    action_type_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[3]'
    select_deleted_xpath = '//li/span[text() = " Deleted "]'
    select_imported_xpath = '//li/span[text() = " Imported "]'
    group_name_from_container_xpath = '//*[@title="*** Corrupt Events ***"]'





