class LocatorsVehiclePage:
    div_page_title = '(//div[@class="title-heading"]//child::*)[1]'
    vehicle_menu_icon = '//div[@mattooltip="Vehicles"]'
    highlighted_vehicle_menu_icon = '//div[@class="tab-parent tab-parent-bgc"]//div[@mattooltip="Vehicles"]//div[@class="icon-label"]'
    add_vehicle_btn = '//button[contains(text(),"Add Vehicle")]'
    popup_title = '//div[@class="container"]//p[@class="addtitle"]'
    group_lbl = '//form//label[contains(text(),"Group name")]'
    vehicle_name_lbl = '//input[@name="vehicleName"]//parent::div//label'
    vin_lbl = '//input[@name="vin"]//parent::div//label'
    location_name_lbl = '//input[@name="location"]//parent::div//label'
    dia_port_lbl = '//select[@name="diagnosticPort"]//parent::div//label'
    group_help_lbl = '//div[starts-with(text()," *If you do not see ")]'
    optional_section_lbl = '//p[contains(@class,"optional")]'
    order_lbl = '//select[@name="quote_number"]//parent::div//label'
    license_state_lbl = '//select[@name="licenseState"]//parent::div//label'
    dvir_lbl = '//select[@name="dvir"]//parent::div//label'
    license_plate_lbl = '//input[@name="licensePlate"]//parent::div//label'
    inactive_reset_btn = '//button[@type="reset"]'
    group_txt_bx = '//div[@class="multi-group-filter"]'
    group_search = '//input[@placeholder="Search Groups"]'
    vehicle_name_txt_bx = '//input[@name="vehicleName"]'
    vin_txt_bx = '//input[@name="vin"]'
    location_name_txt_bx = '//input[@name="location"]'
    dia_port_txt_bx = '//select[@name="diagnosticPort"]'
    order_txt_bx = '//select[@name="quote_number"]'
    license_state_txt_bx = '//select[@name="licenseState"]'
    dvir_txt_bx = '//select[@name="dvir"]'
    license_plate_txt_bx = '//input[@name="licensePlate"]'
    corrupt_group = '//span[contains(text(), "***Corrupt Event***")]'
    done_btn ='//button[starts-with(@class,"multi-group-selector-bottom-done")]'
    recent_vehicle_name = '//td[@id="vehicle_name_0"]'
    recent_date = '//td[@id="vehicle_dateadded_0"]'
    recent_vin = '//td[@id="vehicle_vin_0"]'
    recent_model = '//td[@id="vehicle_model_0"]'
    recent_location_name = '//td[@id="vehicle_location_0"]'
    recent_quote = '//td[@id="vehicle_quote_0"]'
    recent_install_status = '//td[@id="vehicle_status_0"]'
    delete_vehicle_btn = '//button[contains(@class,"delete-btn")]'
    import_vehicle = '//input[@type ="file"]'
    download_template_btn ="//a[@class='download']"
    next_btn = '//button[contains(text(),"Next")]'
    primary_btn = '//button[contains(@class,"primaryBtn")]'
    recent_vehicle_edit_btn = '//a[contains(text(),"automation_vehicle")]'
    group_txt = '//span[@class="multi-group-filter__label"]'
    import_vehicle_btn = '//button[contains(@class,"import_button")]'
    clear_all_btn = '//span[@class="clear_text"]'