class LocatorsDeviceManagement:
    device_tab_xpath = '/html/body/app-root/shell/div/div/navigation/div[1]/div[6]'
    device_management_title_xpath = '//*[text()="Device Management"]'
    error_loading_devices_xpath = '//*[contains(text(), " There was an error loading devices ")]'
    device_count_xpath = '//*[contains(text()," device") or contains(text()," Device")]/parent::div/preceding-sibling::div'
    device_table_text_xpath = '//*[text()="Device"]'
    device_type_table_text_xpath = '//*[text()="Device Type"]'
    asset_table_text_xpath = '//*[@id="sortableContainerVehicleName"]/span[1]'
    group_table_text_xpath = '//*[text()="Group"]'
    status_table_text_xpath = '//*[text()="Status"]'
    last_connected_table_text_xpath = '//*[text()="Last Communicated"]'
    initial_connection_table_text_xpath = '//*[text()="Initial Connection"]'
    group_filter_xpath = '//*[text()=" Select Group(s) "]'
    search_group_filter_textbox_xpath = '//input[@placeholder="Search Groups"]'
    select_searched_group_filter_button_xpath = '//input[@placeholder="Search Groups"]/parent::div//button'
    done_group_filter_button_xpath = '//*[contains(@class, "multi-group-selector-bottom-done lx-btn lx-btn-primary")]'
    clear_group_filter_xpath = '/html/body/app-root/shell/div/div/div/app-device-list/div/div[1]/filter-bar/' \
                               'div/div[2]/div[2]/multi-group-filter/div/i[2]'
    device_type_button_xpath = '//*[@id="typeMultiFilter"]'
    select_device_type_button_xpath = '//*[text()="{0}"]'
    status_filter_button_xpath = '//*[@id="statusMultiFilter"]'
    select_status_button_xpath = '//*[text()="In Service"]'
    search_device_filter_textbox_xpath = '//*[@id="searchInput"]'
    reset_button_xpath = './/*[text()="Reset"]'
    first_row_device_name_xpath = '//cdk-table/cdk-row[1]/cdk-cell[2]//a'
    first_row_device_type_xpath = '//*[text()=" {0} "]'
    first_row_vehicle_name_xpath = '(.//*[contains(@class, "cell-value ng-star-inserted")])[3]'
    first_row_group_name_xpath = '//cdk-table/cdk-row[1]/cdk-cell[5]/span[2]'
    first_row_status_name_xpath = '(.//*[contains(@class, "cdk-cell lytx-table-cell cdk-column-Status")])[1]/span[2]'
    first_row_device_checkbox_xpath = '(.//*[contains(@class, "lx-icon table-checkbox lx-checkbox-inactive")])[1]'
    move_group_tab_xpath = './/*[text()="Move Group"]'
    search_group_move_textbox_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                      'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/input'
    select_group_move_button_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                     'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/ngb-typeahead-window/button'
    done_group_move_button_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                   'multi-group-selector/div/div[3]/button[2]'
    continue_move_group_button_xpath = '//*[text()=" Continue "]'
    change_status_button_xpath = '//*[text()="Change Status"]'
    spare_checkbox_xpath = '(//*[text()="Spare" or @class="lytx-radio-button"])[1]'
    save_change_status_button_xpath = '/html/body/ngb-modal-window/div/div/app-status-modal/lytx-modal-shell/' \
                                      'div/div[2]/div[3]/button[2]'
    select_search_filter_xpath = '//*[@id="multiSearchTypeFilter"]/div/span/span'
    select_device_filter_xpath = '//*[@id="multiSearchTypeFilter"]/div/div/ul/li[1]'
    remove_status_filter = '//*[@id="statusMultiFilter"]//div[2]'
    move_group_success_message = '//*[contains(text(), " Device moved.")]'
    devices_count_xpath = '//*[@data-test-id="filter-headerBar-countValue"]'
    group_row_text_xpath = '//cdk-table/cdk-row[{row}]/cdk-cell[5]/span[2]'

#     View Change history
    view_change_history_xpath = '//*[@ngbtooltip="View Change History"]'
    device_affected_table_text_xpath = '//cdk-header-cell//span[text()="Device Affected"]'
    action_table_text_xpath = '//cdk-header-cell//span[text()="Action"]'
    action_details_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Action Details")]'
    editor_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Editor")]'
    action_date_table_text_xpath = '//cdk-header-cell//span[contains(text(), "Action Date")]'
    device_audit_log_title_xpath = '//*[contains(text(),"Device Audit Log")]'
    search_device_affected_textbox_xpath = '//*[@id="searchInput"]'
    date_filter_xpath = '//*[@class="audit-date"]'
    select_date_range_today_xpath = '//*[@class="audit-date"]//span[contains(@class, "today")]'
    select_actions_filter_xpath = '//*[@class="audit-actions"]'
    download_log_button_xpath = '//*[contains(text(),"Download Log")]'
    download_log_button_disabled_xpath = '//*[@class="audit-download"]//button[@disabled]'
    first_device_affected_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[1]/span[2]'
    no_audit_logs_message_xpath = '//*[contains(@class,"lx-table__table__empty-message")]'
    action_date_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[5]'
    close_view_change_history_xpath = '//*[text()=" Close "]'
    view_change_history_popup_xpath = '//*[@modalcomponentname="DeviceAuditLog"]'
    reset_button_audit_page_xpath = '//*[@class="audit-log-modal-shell"]//*[text()="Reset"]'
    select_added_xpath = '//li/span[contains(text(), "Added")]'
    select_edited_xpath = '//li/span[contains(text(), "Edited")]'
    action_type_text_xpath = '//audit-log-table//cdk-row[1]/cdk-cell[2]'
    select_deleted_xpath = '//li/span[text() = " Deleted "]'
    select_imported_xpath = '//li/span[text() = " Imported "]'
    first_action_details_text_xpath = '//cdk-table/cdk-row[1]/cdk-cell[3]/span[2]/span'

