class LocatorsEquipmentManagement:
    equipment_management_tab_xpath = '//*[contains(text(), "Equipment")]'
    equipment_management_title_xpath = '//*[text()="Equipment Management"]'
    equipment_count_xpath = '//*[@id="filter-bar"]/filter-bar/div/div[2]/div[1]/div[1]/div/div[1]/div'
    add_equipment_button_xpath = '//*[text()=" Add equipment "]'
    equipment_column_name_id = 'sortableContainerAssetName'
    device_column_name_id = 'sortableContainerSerialNumber'
    group_column_name_id = 'sortableContainerGroupName'
    last_connected_column_name_id = 'sortableContainerLastConnectedDate'
    status_column_name_id = 'sortableContainerAssetStatusId'
    group_filter_id = 'multiGroupSelectorIcon'
    group_filter_done_button_xpath = '//*[text()="Done"]'
    equipment_name_textbox_xpath = '//input[@id="equipmentName"]'
    equipment_status_xpath = '//dropdown[@id="status"]//span/span'
    # equipment_status_text_xpath = '//*[@id="status"]/div/span/span/span'
    equipment_status_in_service_xpath = '//*[@id="status"]//*[text()=" In Service "]'
    equipment_search_device_xpath = '//*[@id="deviceSearch"]//input'
    equipment_search_device_result_xpath = '//*[text()="Assigned Device"]/parent::div//button[@type="button"]'
    move_and_continue_id = 'modalShellPrimaryButton'
    create_equipment_button_id = 'submitButton'
    test_equipment_added_xpath = '//cdk-table/cdk-row/cdk-cell[2]/span[2]/a'
    first_checkbox_xpath = '//cdk-table/cdk-row/cdk-cell[1]/div/div/i'
    change_status_button_xpath = '//*[text()="Change Status"]'
    edit_equipment_status_drop_down_xpath = '/html/body/ngb-modal-window/div/div/bulk-equipment-status/bulk-action' \
                                            '-modal/lytx-modal-shell/div/div[2]/div[2]/div[' \
                                            '1]/equipment-status/div/div/dropdown/div/span/i '
    in_service_xpath = '/html/body/ngb-modal-window/div/div/bulk-equipment-status/bulk-action-modal/lytx-modal-shell' \
                       '/div/div[2]/div[2]/div[1]/equipment-status/div/div/dropdown/div/div/ul/li[1] '
    out_of_service_xpath = '/html/body/ngb-modal-window/div/div/bulk-equipment-status/bulk-action-modal/lytx-modal' \
                           '-shell/div/div[2]/div[2]/div[1]/equipment-status/div/div/dropdown/div/div/ul/li[2] '
    spare_xpath = '/html/body/ngb-modal-window/div/div/bulk-equipment-status/bulk-action-modal/lytx-modal-shell/div' \
                  '/div[2]/div[2]/div[1]/equipment-status/div/div/dropdown/div/div/ul/li[3] '
    set_equipment_status_apply_button_id = 'modalShellPrimaryButton'
    status_value_xpath = '//cdk-row[1]/cdk-cell[6]/span[2]'
    first_equipment_in_list_xpath = '//cdk-row[1]/cdk-cell[2]/span[2]/a'
    search_drop_down_xpath = '//div[2]/dropdown[2]/div/span/i '
    equipment_in_drop_down_xpath = '//dropdown//*[text()=" Equipment "]'
    search_textbox_id = 'searchInput'
    root_group_checkbox_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/multi-group-selector' \
                                '/div/div[2]/div/div[2]/div[1]/div/div/span/i '
    equipment_management_status_drop_down_xpath = '//dropdown[@id="statusFilter"]'
    equipment_management_in_service_status_drop_down_xpath = '//dropdown//*[text()=" In Service "]'
    equipment_management_out_of_service_status_drop_down_xpath = '//dropdown//*[text()=" Out Of Service "]'
    equipment_management_spare_status_drop_down_xpath = '//dropdown//*[text()=" Spare "]'
    reset_button_xpath = '//*[text()="Reset"]'
    add_equipment_status_dropdown_xpath = '//dropdown[@id="status"]//span/span'
    add_equipment_in_service_dropdown_xpath = '//*[text()=" In Service "]'
    add_equipment_out_of_service_dropdown_xpath = '//li//*[text()=" Out Of Service "]'
    add_equipment_spare_dropdown_xpath = '//*[text()=" Spare "]'
    last_connected_filter_xpath = '//lx-date-range-filter//*[text()="Last Connected"]'
    last_30_days_xpath = '//*[text()=" Last 30 Days "]'
    apply_button_last_connected_xpath = '//*[text()="Apply"]'
    select_the_first_equipment_xpath = '//cdk-row[1]/cdk-cell[1]/div/div/i'
    move_group_button_xpath = '//*[text()="Move Group"]'
    detach_button_xpath = '//*[text()="Detach Device"]'
    apply_detach_id = 'modalShellPrimaryButton'
    detach_message_xpath = '//*[@id="toast-container"]/div/div'
    search_group_textbox_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                 'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/input'
    select_searched_group_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal/' \
                                  'multi-group-selector/div/div[1]/div[2]/div/lytx-typeahead/div/' \
                                  'ngb-typeahead-window/button'
    move_group_done_button_xpath = '/html/body/ngb-modal-window/div/div/multi-group-selector-modal' \
                                   '/multi-group-selector/div/div[3]/button[2]'
    move_group_continue_button_xpath = '/html/body/ngb-modal-window/div/div/bulk-equipment-group/' \
                                       'bulk-action-modal/lytx-modal-shell/div/div[2]/div[3]/button[2]'
    group_name_of_first_equipment_xpath = '//cdk-table/cdk-row[1]/cdk-cell[4]/span[2]'
    group_of_first_equipment_xpath = '//*[@id="groupSelector"]//span'
    cancel_button_xpath = '//*[text()=" Cancel "]'
    delete_equipment_button_xpath = '//*[text()="Delete Equipment"]'
    confirm_button_xpath = '//*[text()=" Confirm "]'
    select_all_equipment_button = '//cdk-table/cdk-header-row/cdk-header-cell[1]/i'
    device_1st_equipment_xpath = '//cdk-table/cdk-row/cdk-cell[3]/span[2]'
    add_equip_Page_title_xpath = '//*[text()="Add equipment "]'
    equipment_created_success_message_xpath = '//*[contains(text(), "successfully created")]'
    equipment_deleted_success_message_xpath = '//*[contains(text(), "equipment deleted")]'
    group_filter_xpath = '//div[@class="multi-group-filter"]'
    search_filter_xpath = '//*[@id="multiTypeFilter"]'
    more_options_xpath = '//*[contains(text(),"More Options")]'
    paginator_xpath = '//*[contains(@class, "paginator")]'
    device_column_sorting_xpath = '(//*[@class="arrow-down"])[2]'
    equipment_with_attached_devices_count_xpath = ''
