class LocatorsConsentReport:
    consent_report_tab_xpath = '//*[contains(text()," Consent Report")]'
    group_filter_xpath = '//*[@class="group-filter"]'
    status_filter_id = 'consentStatusDropdown'
    search_name_or_id_id = 'textSearch'
    reset_button_xpath = '//*[@data-test-id="reset-button-text"]'
    driver_count_xpath = '//*[@class="filter-header-bar__title__count"]'
    facial_id_tab_xpath = '//*[@class="tab-text" and text()="Facial ID"]'
    distraction_and_fatigue_detection_tab_xpath = '//*[@class="tab-text" and text()="Distraction and Fatigue Detection"]'
    video_safety_tab_xpath = '//*[@class="tab-text" and text()="Video Safety"]'
    search_by_group_field_xpath = '//*[@data-test-id="typeahead-search-input"]'
    select_group_xpath = '(//*[contains(@class, "dropdown-item")])[1]'
    done_button_xpath = '//*[text()="Done"]'
    first_group_name_xpath = '(//cdk-row/cdk-cell[3]/span[2])[1]'
    status_filter_xpath = '(//*[@class="dropdown__select__content"])[1]'
    not_received_status_button_xpath = '//*[text()=" Not Received "]'
    received_status_button_xpath = '//*[text()=" Received "]'
    revoked_status_button_xpath = '//*[text()=" Revoked "]'
    opted_out_status_button_xpath = '//*[text()=" Opted Out "]'
    search_name_xpath = '//*[@id="searchInput"]'
    first_row_driver_name_xpath = '(//cdk-row/cdk-cell[2]/span[2])[1]'
    name_column_label_xpath = '//*[@id="sortableContainerdriverName"]'
    groups_column_label_xpath = '//*[@id="sortableContainergroupName"]'
    status_column_label_xpath = '//*[@id="sortableContainerStatus"]'
    sent_date_column_label_xpath = '//*[@id="sortableContainerSentDate"]'
    received_date_column_label_xpath = '//*[@id="sortableContainerReceivedDate"]'
    clear_all_option_xpath = '//*[text()="Clear All "]'
    download_pdf_option_xpath = '//*[text()="Download PDF"]'
    revoke_consent_option_xpath = '//*[text()="Revoke Consent"]'
    csv_option_xpath = '//*[text()=" CSV "]'
    consent_report_title_xpath = '//*[@class="consent-report__page-header"]'
    get_first_row_status_xpath = '(//cdk-row/cdk-cell[4]/span[2])[1]'
    download_pdf_xpath = '(//*[@class="action-link pdf-link"])[1]'
    last_page_number_xpath = '//*[@class="paging__pages--right"]//preceding::span[1]'
    get_last_page_driver_name_xpath = '((//cdk-cell[contains(@class, "cdk-column-Name")])[1]//span[2])[1]'
    enable_facial_id_link_xpath = '//*[@class="lx-btn lx-btn-primary enable-product-actions__button"]'
    user_count_xpath = '(//div[div[1][normalize-space()="***DC4DC"]]/div[2])[2]'
    enable_product_cancel_button_id = 'fullScreenModalShellSecondaryButton'
    save_changes_button_xpath = '//*[@id="submit-button"]'
    password_textbox_xpath = '//*[@id="password-form"]/lytx-input/div/div[2]/input'
