class LocatorsCoachesProfile:
    coach_profile_text_xpath = '//*[@data-test-id="coachProfile-pageHeader-text"]'
    employee_id_text_xpath = '//*[@data-test-id="coachProfile-info-section"]//*[contains(text(), "Employee ID")]'
    group_text_xpath = '//*[@data-test-id="coachProfile-info-section"]//lx-data-bar-label//*[contains(text(), "Group")]'
    email_text_xpath = '//*[@data-test-id="coachProfile-info-section"]//lx-data-bar-label//*[contains(text(), "Email")]'
    last_login_text_xpath = '//*[@data-test-id="coachProfile-info-section"]//*[contains(text(), "Last Login")]'
    coaching_effectiveness_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[text()="COACHING EFFECTIVENESS"]'
    coached_behaviors_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[contains(text(), "COACHED BEHAVIORS")]'
    repeated_behaviors_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[contains(text(), "REPEATED BEHAVIORS")]'
    coached_events_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[contains(text(), "COACHED EVENTS")]'
    avg_days_to_coach_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[contains(text(), "AVG DAYS TO COACH")]'
    with_notes_text_xpath = '//*[@data-test-id="coachProfile-effectivenessSummary-table"]//*[contains(text(), "WITH NOTES")]'
    coaching_effectiveness_graph_text_xpath = '//lytx-trends/div/div[1]/div[1]'
    driver_text_xpath = '//*[@data-test-id="coachProfile-drivers-section"]//span[text()="Driver"]'
    drivers_coaching_effectiveness_text_xpath = '//*[@data-test-id="coachProfile-drivers-section"]//span[text()="Coaching Effectiveness"]'
    drivers_behaviors_group_text_xpath = '//*[@data-test-id="coachProfile-drivers-section"]//span[text()="Behavior Groups"]'
    drivers_coached_behaviors_text_xpath = '//*[@data-test-id="coachProfile-drivers-section"]//span[text()="Coached Behaviors"]'
    drivers_repeated_behaviors_text_xpath = '//*[@data-test-id="coachProfile-drivers-section"]//span[text()="Repeated Behaviors"]'
    behavior_groups_tab_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()=" Behavior Groups "]'
    behavior_group_text_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()="Behavior Group"]'
    behavior_coaching_effectiveness_text_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()="Coaching Effectiveness"]'
    behavior_drivers_text_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()="Drivers"]'
    coached_behaviors_group_text_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()="Coached Behaviors"]'
    repeated_behaviors_group_text_xpath = '//*[@data-test-id="coachProfile-drivers-tab"]//*[text()="Repeated Behaviors"]'
