class LocatorsInspectionReportPage:
    inspection_report_title_xpath = '//*[text()=" Inspection report "]'
    report_id_title_xpath = '//*[text()="Report Id"]'
    inspection_type_title_xpath = '//*[text()="Inspection Type"]'
    driver_title_xpath = '//*[text()="Driver"]'
    report_date_title_xpath = '//*[text()="Report Date"]'
    status_title_xpath = '//*[text()="Status"]'
    location_title_xpath = '//*[text()="Location"]'
    license_plate_title_int_xpath = '//*[text()="License plate"]'
    license_plate_title_stg_xpath = '//*[text()="Trailer license plate"]'
    odometer_title_xpath = '//*[text()="Odometer"]'
    driver_signature_name_title_xpath = '//*[text()="Driver signature"]'
    mechanic_signature_title_xpath = '//div[text()=" Mechanic/Agent signature "]'
    add_notes_button_xpath = '//*[text()=" Add Note "]'
    notes_textbox_xpath = '//textarea[@type="text"]'
    save_notes_button_xpath = '//*[text()=" Save "]'
    added_note_text_xpath = '(//div[@class="note__text"])[2]'
    keboo_button_xpath = '(//div[@class="dropdown"])[2]'
    edit_dropdown_xpath = '//li/span[text()=" Edit "]'
    note_edit_textbox_xpath = '//*[text()="fix brake, auto update note"]'
    delete_dropdown_xpath = '//li/span[text()=" Delete "]'
    back_button_xpath = '//*[text()="< Back"]'

    resolve_button_xpath = '//*[text()=" Resolve "]'
    repaired_button_xpath = '//*[text()=" Repaired "]'
    no_repair_needed_button_xpath = '//*[text()=" No Repair Needed "]'
    repaired_text_xpath = '//*[text()="Repaired"]'
    reopen_text_xpath = '//*[text()=" Reopen "]'
    no_repair_needed_text_xpath = '//*[text()="No Repair Needed"]'
